
let vocab_5001_5020 = [
   ["אוֹת", "sign", "<br>", "<br>", "", ""],
   ["אַלְמָנָה", "widow", "<br>", "<br>", "", ""],
   ["אָמֵן", "amen", "<br>", "<br>", "", ""],
   ["ארך", "(Hi) to prolong, be prolonged", "<br>", "<br>", "", ""],
   ["ארר", "(Q Pass) to be cursed", "<br>", "<br>", "", ""],
   ["בער", "(Pi) to purge", "<br>", "<br>", "", ""],
   ["בְּרָכָה", "blessing", "<br>", "<br>", "", ""],
   ["גֵּר", "sojourner", "<br>", "<br>", "", ""],
   ["זְרוֹעַ", "arm", "<br>", "<br>", "", ""],
   ["חָזָק", "strong, mighty", "<br>", "<br>", "", ""],
   ["יָתוֹם", "orphan", "<br>", "<br>", "", ""],
   ["לוּחַ", "tablet", "<br>", "<br>", "", ""],
   ["למד", "(Q) to learn; (Pi) teach", "<br>", "<br>", "", ""],
   ["נַעֲרָה", "girl, young woman", "<br>", "<br>", "", ""],
   ["עֵ֫בֶר", "region beyond", "<br>", "<br>", "", ""],
   ["עֵד", "witness", "<br>", "<br>", "", ""],
   ["עֲרָבָה", "desert plain, Arabah", "<br>", "<br>", "", ""],
   ["קְלָלָה", "curse", "<br>", "<br>", "", ""],
   ["שׁוֹר", "ox", "<br>", "<br>", "", ""],
   ["שׁמד", "(Ni) to be destroyed; (Hi) destroy", "<br>", "<br>", "", ""],
]

let vocab_5021_5040 = [
   ["אבה", "(Q) to be willing, yield", "<br>", "<br>", "", ""],
   ["אֶבְיוֹן", "needy", "<br>", "<br>", "", ""],
   ["אָמָה", "female servant, female slave", "<br>", "<br>", "", ""],
   ["בַּרְזֶל", "iron", "<br>", "<br>", "", ""],
   ["דְּבַשׁ", "honey", "<br>", "<br>", "", ""],
   ["חֵטְא", "sin, offense", "<br>", "<br>", "", ""],
   ["חָלָב", "milk", "<br>", "<br>", "", ""],
   ["חֵ֫לֶק", "portion", "<br>", "<br>", "", ""],
   ["חרם", "(Hi) to ban, devote, destroy", "<br>", "<br>", "", ""],
   ["טָמֵא", "unclean", "<br>", "<br>", "", ""],
   ["כֶּ֫רֶם", "vineyard", "<br>", "<br>", "", ""],
   ["מהר", "(Pi) to hasten, hurry, do quickly", "<br>", "<br>", "", ""],
   ["מוֹפֵת", "sign", "<br>", "<br>", "", ""],
   ["מרה", "(Q) to be rebellious; (Hi) rebel", "<br>", "<br>", "", ""],
   ["נדח", "(Ni) to be drawn away, be banished, go astray; (Hi) draw away, banish, lead astray", "<br>", "<br>", "", ""],
   ["נחל", "(Q) to inherit, possess; (Hi) give as an inheritance, cause to inherit", "<br>", "<br>", "", ""],
   ["נסה", "(Pi) to test, try", "<br>", "<br>", "", ""],
   ["צוּר", "rock", "<br>", "<br>", "", ""],
   ["קָצֶה", "end", "<br>", "<br>", "", ""],
   ["קָרוֹב", "near", "<br>", "<br>", "", ""],
]

let vocab_5041_5060 = [
   ["אַחֲרוֹן", "last, latter, western", "<br>", "<br>", "", ""],
   ["אַחֲרִית", "end", "<br>", "<br>", "", ""],
   ["אָלָה", "oath", "<br>", "<br>", "", ""],
   ["אמן", "(Ni) to be trustworthy, be faithful, be continual; (Hi) believe, trust", "<br>", "<br>", "", ""],
   ["אמץ", "(Q) to be strong, be courageous; (Pi) strengthen, harden", "<br>", "<br>", "", ""],
   ["ארשׂ", "(Pi) to betroth; (Pu) be betrothed", "<br>", "<br>", "", ""],
   ["דבק", "(Q) to cling; (Hi) make cling", "<br>", "<br>", "", ""],
   ["דָּגָן", "grain", "<br>", "<br>", "", ""],
   ["חַג", "feast, festival", "<br>", "<br>", "", ""],
   ["טַף", "children", "<br>", "<br>", "", ""],
   ["יַחְדָּו", "together", "<br>", "<br>", "", ""],
   ["יְרֻשָּׁה", "possession", "<br>", "<br>", "", ""],
   ["מכר", "(Q) to sell; (Ni) be sold; (Hith) offer oneself for sale", "<br>", "<br>", "", ""],
   ["מַעֲשֵׂר", "tithe", "<br>", "<br>", "", ""],
   ["ענה", "(Pi) to humble, humiliate, violate", "<br>", "<br>", "", ""],
   ["רֵאשִׁית", "beginning, first", "<br>", "<br>", "", ""],
   ["רצח", "(Q) to murder", "<br>", "<br>", "", ""],
   ["שׂבע", "(Q) to be satisfied, be full", "<br>", "<br>", "", ""],
   ["שׁוֹטֵר", "officer", "<br>", "<br>", "", ""],
   ["תִּירוֹשׁ", "new wine", "<br>", "<br>", "", ""],
]

let vocab_5061_5080 = [
   ["בֶּ֫טֶן", "belly, womb", "<br>", "<br>", "", ""],
   ["זוב", "(Q) to flow", "<br>", "<br>", "", ""],
   ["חֲמוֹר", "male donkey", "<br>", "<br>", "", ""],
   ["טָהוֹר", "clean", "<br>", "<br>", "", ""],
   ["יִצְהָר", "oil", "<br>", "<br>", "", ""],
   ["כעס", "(Pi, Hi) to provoke to anger", "<br>", "<br>", "", ""],
   ["מוּל", "in front of, opposite", "<br>", "<br>", "", ""],
   ["מָטָר", "rain", "<br>", "<br>", "", ""],
   ["מַכָּה", "wound", "<br>", "<br>", "", ""],
   ["מִשְׁלָח", "undertaking", "<br>", "<br>", "", ""],
   ["מַת", "man, person", "<br>", "<br>", "", ""],
   ["נֵ֫דֶר", "vow", "<br>", "<br>", "", ""],
   ["נָקִי", "innocent, free", "<br>", "<br>", "", ""],
   ["סתר", "(Ni) to be hidden; (Hi) hide", "<br>", "<br>", "", ""],
   ["עָצוּם", "mighty", "<br>", "<br>", "", ""],
   ["פדה", "(Q) to redeem", "<br>", "<br>", "", ""],
   ["שִׂמְלָה", "garment", "<br>", "<br>", "", ""],
   ["שִׁירָה", "song", "<br>", "<br>", "", ""],
   ["שָׁלָל", "spoil, plunder", "<br>", "<br>", "", ""],
   ["תְּבוּאָה", "produce, harvest", "<br>", "<br>", "", ""],
]

let vocab_5081_5100 = [
   ["אֵיכָה", "how?", "<br>", "<br>", "", ""],
   ["בדל", "(Hi) to set apart", "<br>", "<br>", "", ""],
   ["בְּתוּלִים", "(evidence of) virginity", "<br>", "<br>", "", ""],
   ["גֹּ֫דֶל", "greatness", "<br>", "<br>", "", ""],
   ["זַ֫יִת", "olive, olive tree, olive orchard", "<br>", "<br>", "", ""],
   ["זרע", "(Q) to sow; (Ni) be sown", "<br>", "<br>", "", ""],
   ["חוס", "(Q) to pity", "<br>", "<br>", "", ""],
   ["חָלָל", "slain", "<br>", "<br>", "", ""],
   ["חרה", "(Q) to burn", "<br>", "<br>", "", ""],
   ["יסר", "(Pi) to discipline", "<br>", "<br>", "", ""],
   ["יצב", "(Hith) to stand", "<br>", "<br>", "", ""],
   ["מֶ֫גֶד", "excellence", "<br>", "<br>", "", ""],
   ["מִזְרָח", "east, rising (of the sun)", "<br>", "<br>", "", ""],
   ["מָצוֹר", "siege", "<br>", "<br>", "", ""],
   ["נדר", "(Q) to vow", "<br>", "<br>", "", ""],
   ["נטע", "(Q) to plant", "<br>", "<br>", "", ""],
   ["נכר", "(Pi) to misunderstand; (Hi) acknowledge, recognize", "<br>", "<br>", "", ""],
   ["נָכְרִי", "foreign, foreigner", "<br>", "<br>", "", ""],
   ["תְּמוּנָה", "form", "<br>", "<br>", "", ""],
   ["תמם", "(Q) to end, cease, perish", "<br>", "<br>", "", ""],
]

let vocab_5101_5120 = [
   ["אַוָּה", "desire", "<br>", "<br>", "", ""],
   ["אַיָּל", "deer", "<br>", "<br>", "", ""],
   ["אֶ֫לֶף", "cattle", "<br>", "<br>", "", ""],
   ["אנף", "(Hith) to be angry", "<br>", "<br>", "", ""],
   ["בְּלִי", "without", "<br>", "<br>", "", ""],
   ["עבט", "(Q) to borrow, take a pledge; (Hi) lend", "<br>", "<br>", "", ""],
   ["עוד", "(Hi) to warn, testify, call to testify", "<br>", "<br>", "", ""],
   ["עָנָן", "cloud", "<br>", "<br>", "", ""],
   ["פֹּה", "here", "<br>", "<br>", "", ""],
   ["פֶּ֫סֶל", "idol, graven image", "<br>", "<br>", "", ""],
   ["פַּרְסָה", "hoof", "<br>", "<br>", "", ""],
   ["קצף", "(Q) to be angry; (Hi) provoke, anger", "<br>", "<br>", "", ""],
   ["רָחוֹק", "far", "<br>", "<br>", "", ""],
   ["רִיב", "dispute", "<br>", "<br>", "", ""],
   ["רעע", "(Q) to be bad, be evil; (Hi) do evil", "<br>", "<br>", "", ""],
   ["שֶׂה", "sheep, lamb", "<br>", "<br>", "", ""],
   ["שְׂמֹאל", "left", "<br>", "<br>", "", ""],
   ["שְׁמִטָּה", "remission (of debts)", "<br>", "<br>", "", ""],
   ["שׁרת", "(Pi) to minister", "<br>", "<br>", "", ""],
   ["תַּבְנִית", "likeness, form", "<br>", "<br>", "", ""],
]

let vocab_5121_5140 = [
   ["בָּצוּר", "inaccessible, unassailable", "<br>", "<br>", "", ""],
   ["בְּתוּלָה", "virgin", "<br>", "<br>", "", ""],
   ["גרה", "(Hith) to contend", "<br>", "<br>", "", ""],
   ["גֵּרָה", "cud", "<br>", "<br>", "", ""],
   ["דרך", "(Q) to tread, walk", "<br>", "<br>", "", ""],
   ["הֵן", "behold", "<br>", "<br>", "", ""],
   ["חֶ֫בֶל", "region", "<br>", "<br>", "", ""],
   ["חָדָשׁ", "new", "<br>", "<br>", "", ""],
   ["טֶ֫נֶא", "basket", "<br>", "<br>", "", ""],
   ["ירה", "(Hi) to teach", "<br>", "<br>", "", ""],
   ["כּוֹכָב", "star", "<br>", "<br>", "", ""],
   ["לוה", "(Q) to borrow; (Hi) lend", "<br>", "<br>", "", ""],
   ["לָ֫מוֹ", "to them, for them", "<br>", "<br>", "", ""],
   ["מוּם", "defect, blemish", "<br>", "<br>", "", ""],
   ["מוֹרָא", "fear, terror", "<br>", "<br>", "", ""],
   ["מחה", "(Q) to wipe out; (Ni) be wiped out", "<br>", "<br>", "", ""],
   ["מִין", "kind", "<br>", "<br>", "", ""],
   ["נְבֵלָה", "carcass, corpse", "<br>", "<br>", "", ""],
   ["נֶ֫גַע", "plague, assault", "<br>", "<br>", "", ""],
   ["נְדָבָה", "freewill offering", "<br>", "<br>", "", ""],
]

let vocab_5141_5160 = [
   ["נשׁך", "(Q) to pay interest; (Hi) charge interest", "<br>", "<br>", "", ""],
   ["נשׁל", "(Q) to drop off, clear away", "<br>", "<br>", "", ""],
   ["נשׂג", "(Hi) to overtake", "<br>", "<br>", "", ""],
   ["סקל", "(Q) to stone", "<br>", "<br>", "", ""],
   ["סֵ֫תֶר", "secrecy (בַּסֵּ֫תֶר secretly)", "<br>", "<br>", "", ""],
   ["עֲבוֹט", "pledge", "<br>", "<br>", "", ""],
   ["עֶגְלָה", "heifer", "<br>", "<br>", "", ""],
   ["עֵנָב", "grape", "<br>", "<br>", "", ""],
   ["עָנִי", "poor", "<br>", "<br>", "", ""],
   ["עֹ֫רֶף", "(back of the) neck", "<br>", "<br>", "", ""],
   ["ערץ", "(Q) to be in dread, tremble", "<br>", "<br>", "", ""],
   ["עַשְׁתֶּ֫רֶת", "young", "<br>", "<br>", "", ""],
   ["פֶּ֫סַח", "Passover", "<br>", "<br>", "", ""],
   ["פרס", "(Hi) to have hoofs, divide (the hoof)", "<br>", "<br>", "", ""],
   ["צְבִי", "gazelle", "<br>", "<br>", "", ""],
   ["צַר", "adversary", "<br>", "<br>", "", ""],
   ["קשׁה", "(Q) to be difficult; (Hi) harden", "<br>", "<br>", "", ""],
   ["קָשֶׁה", "hard, stubborn", "<br>", "<br>", "", ""],
   ["רפה", "(Hi) to leave (alone)", "<br>", "<br>", "", ""],
   ["שׂושׂ", "(Q) to rejoice", "<br>", "<br>", "", ""],
]

let vocab_5161_5180 = [
   ["אוה", "(Pi, Hith) to desire", "<br>", "<br>", "", ""],
   ["אֵיפָה", "ephah (unit of measure)", "<br>", "<br>", "", ""],
   ["אֹ֫כֶל", "food", "<br>", "<br>", "", ""],
   ["אֵל", "these", "<br>", "<br>", "", ""],
   ["אֶ֫פֶס", "end, nothing, only", "<br>", "<br>", "", ""],
   ["אֲשֵׁרָה", "Asherah, sacred pole", "<br>", "<br>", "", ""],
   ["בִּגְלַל", "(= בְּ + גָּלָל) because of", "<br>", "<br>", "", ""],
   ["בזז", "(Q) to plunder", "<br>", "<br>", "", ""],
   ["בֶּ֫טַח", "security, safety", "<br>", "<br>", "", ""],
   ["בלה", "(Q) to wear out", "<br>", "<br>", "", ""],
   ["בעל", "(Q) to marry; (Q Pass) be married", "<br>", "<br>", "", ""],
   ["בער", "(Q) to burn", "<br>", "<br>", "", ""],
   ["בִּקְעָה", "valley, plain", "<br>", "<br>", "", ""],
   ["גור", "(Q) to fear, be afraid", "<br>", "<br>", "", ""],
   ["גַּיְא", "valley", "<br>", "<br>", "", ""],
   ["שָׁבוּעַ", "week", "<br>", "<br>", "", ""],
   ["שֶׁ֫גֶר", "offspring, increase", "<br>", "<br>", "", ""],
   ["שֹׁ֫חַד", "bribe", "<br>", "<br>", "", ""],
   ["תעב", "(Pi) to abhor", "<br>", "<br>", "", ""],
   ["תפשׂ", "(Q) to seize", "<br>", "<br>", "", ""],
]

let vocab_5181_5200 = [
   ["גֶּ֫פֶן", "vine", "<br>", "<br>", "", ""],
   ["זיד", "(Hi) to be presumptuous", "<br>", "<br>", "", ""],
   ["חבל", "(Q) to take in pledge", "<br>", "<br>", "", ""],
   ["חֵיק", "bosom", "<br>", "<br>", "", ""],
   ["חֵ֫לֶב", "fat", "<br>", "<br>", "", ""],
   ["חֲלוֹם", "dream", "<br>", "<br>", "", ""],
   ["חֳלִי", "sickness", "<br>", "<br>", "", ""],
   ["חלם", "(Q) to dream", "<br>", "<br>", "", ""],
   ["חלץ", "(Q) to take off; (Q Pass) be taken off, be equipped", "<br>", "<br>", "", ""],
   ["חנן", "(Q) to be gracious to; (Hith) seek pity, implore", "<br>", "<br>", "", ""],
   ["חסר", "(Q) to lack", "<br>", "<br>", "", ""],
   ["חפץ", "(Q) to delight, desire, be willing", "<br>", "<br>", "", ""],
   ["חָפְשִׁי", "free", "<br>", "<br>", "", ""],
   ["חצב", "(Q) to hew, dig; (Q Pass) be hewn", "<br>", "<br>", "", ""],
   ["חֵ֫רֶם", "ban, devoted thing", "<br>", "<br>", "", ""],
   ["חשׁק", "(Q) to love, desire", "<br>", "<br>", "", ""],
   ["טוֹבָה", "goodness, prosperity", "<br>", "<br>", "", ""],
   ["טַל", "dew", "<br>", "<br>", "", ""],
   ["יְבָמָה", "brother’s wife", "<br>", "<br>", "", ""],
   ["יֶ֫תֶר", "remainder", "<br>", "<br>", "", ""],
]

let vocab_5201_5220 = [
   ["מוֹשִׁיעַ", "rescuer, savior", "<br>", "<br>", "", ""],
   ["מַ֫טָּה", "downward", "<br>", "<br>", "", ""],
   ["מַסָּה", "trial", "<br>", "<br>", "", ""],
   ["מַסֵּכָה", "molten image", "<br>", "<br>", "", ""],
   ["מַצֵּבָה", "pillar", "<br>", "<br>", "", ""],
   ["מַצָּה", "unleavened bread", "<br>", "<br>", "", ""],
   ["מָצוֹק", "distress", "<br>", "<br>", "", ""],
   ["נגף", "(Ni) to be defeated", "<br>", "<br>", "", ""],
   ["נַ֫עַל", "sandal", "<br>", "<br>", "", ""],
   ["נָקָם", "vengeance", "<br>", "<br>", "", ""],
   ["נשׁא", "(Q, Hi) to lend", "<br>", "<br>", "", ""],
   ["נֶ֫שֶׁךְ", "interest", "<br>", "<br>", "", ""],
   ["נֶ֫שֶׁר", "eagle", "<br>", "<br>", "", ""],
   ["סְגֻלָּה", "possession", "<br>", "<br>", "", ""],
   ["סוּף", "reeds", "<br>", "<br>", "", ""],
   ["סֻכָּה", "booth", "<br>", "<br>", "", ""],
   ["עֵדוּת", "testimony, decree", "<br>", "<br>", "", ""],
   ["עוֹף", "bird, flying creature", "<br>", "<br>", "", ""],
   ["עִוֵּר", "blind", "<br>", "<br>", "", ""],
   ["עֶלְיוֹן", "high, Most High", "<br>", "<br>", "", ""],
]

let vocab_5221_5240 = [
   ["עלם", "(Hith) to be hidden, ignore", "<br>", "<br>", "", ""],
   ["עִמָּד", "with", "<br>", "<br>", "", ""],
   ["עֵ֫שֶׂב", "grass, plant", "<br>", "<br>", "", ""],
   ["עשׂר", "(Pi) to tithe", "<br>", "<br>", "", ""],
   ["עשׁק", "(Q) to oppress; (Q Pass) be oppressed", "<br>", "<br>", "", ""],
   ["פוץ", "(Hi) to scatter", "<br>", "<br>", "", ""],
   ["פַּ֫חַד", "dread, fear", "<br>", "<br>", "", ""],
   ["פלא", "(Ni) to be difficult, be hard; (Hi) make wonderful, make extraordinary", "<br>", "<br>", "", ""],
   ["פָּסִיל", "graven image", "<br>", "<br>", "", ""],
   ["צוק", "(Hi) to distress", "<br>", "<br>", "", ""],
   ["צור", "(Q) to besiege, bind", "<br>", "<br>", "", ""],
   ["צעק", "(Q) to cry out", "<br>", "<br>", "", ""],
   ["צִפּוֹר", "bird", "<br>", "<br>", "", ""],
   ["קָדְקֹד", "crown of the head", "<br>", "<br>", "", ""],
   ["קהל", "(Hi) to gather (a group), assemble (a group)", "<br>", "<br>", "", ""],
   ["קָמָה", "standing grain", "<br>", "<br>", "", ""],
   ["קנא", "(Pi, Hi) to provoke to jealousy", "<br>", "<br>", "", ""],
   ["קַנָּא", "jealous", "<br>", "<br>", "", ""],
   ["קֵץ", "end", "<br>", "<br>", "", ""],
   ["רֹאשׁ", "bitter herb, poisonous herb, venom", "<br>", "<br>", "", ""],
]

let vocab_5241_5260 = [
   ["אוֹצָר", "treasury", "<br>", "<br>", "", ""],
   ["אזן", "(Hi) to hear, listen", "<br>", "<br>", "", ""],
   ["אחר", "(Pi) to delay", "<br>", "<br>", "", ""],
   ["אֱלוֹהַּ", "God", "<br>", "<br>", "", ""],
   ["אִמְרָה", "word, speech", "<br>", "<br>", "", ""],
   ["אֶפְרֹחַ", "young bird", "<br>", "<br>", "", ""],
   ["רְבָבָה", "ten thousand", "<br>", "<br>", "", ""],
   ["רבץ", "(Q) to lie down, settle", "<br>", "<br>", "", ""],
   ["רחב", "(Hi) to enlarge", "<br>", "<br>", "", ""],
   ["רַךְ", "tender", "<br>", "<br>", "", ""],
   ["רפא", "(Q) to heal; (Ni) be healed", "<br>", "<br>", "", ""],
   ["רִשְׁעָה", "wickedness", "<br>", "<br>", "", ""],
   ["שְׁבִי", "captivity", "<br>", "<br>", "", ""],
   ["שְׁבִיעִי", "seventh", "<br>", "<br>", "", ""],
   ["שָׁוְא", "vanity, falsehood, emptiness", "<br>", "<br>", "", ""],
   ["שָׁלֵם", "whole", "<br>", "<br>", "", ""],
   ["שִׁלְשׁוֹם", "day before yesterday, time past", "<br>", "<br>", "", ""],
   ["שֵׁן", "tooth", "<br>", "<br>", "", ""],
   ["תְּמוֹל", "previously, yesterday", "<br>", "<br>", "", ""],
   ["תְּרוּמָה", "offering, contribution", "<br>", "<br>", "", ""],
]

let vocab_5261_5280 = [
   ["אֵ֫צֶל", "beside", "<br>", "<br>", "", ""],
   ["אֹ֫רֶךְ", "length", "<br>", "<br>", "", ""],
   ["אָשֵׁד", "slope, hill", "<br>", "<br>", "", ""],
   ["אתה", "(Q) to come", "<br>", "<br>", "", ""],
   ["באר", "(Pi) to make plain", "<br>", "<br>", "", ""],
   ["בָּדָד", "alone", "<br>", "<br>", "", ""],
   ["בֵּיצָה", "egg", "<br>", "<br>", "", ""],
   ["בְּלִיַּ֫עַל", "worthlessness", "<br>", "<br>", "", ""],
   ["בשׁל", "(Pi) to boil", "<br>", "<br>", "", ""],
   ["גַּאֲוָה", "majesty, pride", "<br>", "<br>", "", ""],
   ["גָּבֹהַּ", "high", "<br>", "<br>", "", ""],
   ["גִּבְעָה", "hill", "<br>", "<br>", "", ""],
   ["גֶּ֫בֶר", "man", "<br>", "<br>", "", ""],
   ["גדע", "(Pi) to hew down", "<br>", "<br>", "", ""],
   ["גור", "(Q) to sojourn, dwell", "<br>", "<br>", "", ""],
   ["גזל", "(Q Pass) to be robbed", "<br>", "<br>", "", ""],
   ["גנב", "(Q) to steal", "<br>", "<br>", "", ""],
   ["גַּרְזֶן", "ax", "<br>", "<br>", "", ""],
   ["גֹּ֫רֶן", "threshing floor", "<br>", "<br>", "", ""],
   ["גרע", "(Q) to take away", "<br>", "<br>", "", ""],
]

let vocab_5281_5300 = [
   ["דַּי", "sufficiency, enough", "<br>", "<br>", "", ""],
   ["דִּין", "judgment", "<br>", "<br>", "", ""],
   ["דֶּ֫לֶת", "door, gate", "<br>", "<br>", "", ""],
   ["דַּ֫עַת", "knowledge", "<br>", "<br>", "", ""],
   ["הדף", "(Q) to thrust, drive out", "<br>", "<br>", "", ""],
   ["הפך", "(Q) to turn, overturn", "<br>", "<br>", "", ""],
   ["זָדוֹן", "presumptuousness", "<br>", "<br>", "", ""],
   ["זוּלָה", "except, only", "<br>", "<br>", "", ""],
   ["זְכוּר", "male", "<br>", "<br>", "", ""],
   ["זָכָר", "male", "<br>", "<br>", "", ""],
   ["זֵ֫כֶר", "memory", "<br>", "<br>", "", ""],
   ["זָנָב", "tail", "<br>", "<br>", "", ""],
   ["זנה", "(Q) to be a harlot, act as a harlot", "<br>", "<br>", "", ""],
   ["זָר", "strange", "<br>", "<br>", "", ""],
   ["חדל", "(Q) to cease, refrain", "<br>", "<br>", "", ""],
   ["חטב", "(Q) to hew, cut", "<br>", "<br>", "", ""],
   ["חִטָּה", "wheat", "<br>", "<br>", "", ""],
   ["חיל", "(Q) to writhe; (Polel) give birth", "<br>", "<br>", "", ""],
   ["חַלָּמִישׁ", "flint", "<br>", "<br>", "", ""],
   ["חלק", "(Q) to allot", "<br>", "<br>", "", ""],
]


let deuteronomy_decks = [
   null,
   vocab_5001_5020,
   vocab_5021_5040,
   vocab_5041_5060,
   vocab_5061_5080,
   vocab_5081_5100,
   vocab_5101_5120,
   vocab_5121_5140,
   vocab_5141_5160,
   vocab_5161_5180,
   vocab_5181_5200,
   vocab_5201_5220,
   vocab_5221_5240,
   vocab_5241_5260,
   vocab_5261_5280,
   vocab_5281_5300,
]
