
let vocab_1001_1020 = [
   ["אמר", "(Q) to say; (Q Pass, Ni) be said", "<br>", "<br>", "", ""],
   ["אֶל", "to, toward", "<br>", "<br>", "", ""],
   ["אֱלֹהִים", "God, gods", "<br>", "<br>", "", ""],
   ["אֲשֶׁר", "that, which", "<br>", "<br>", "", ""],
   ["אֵת", "(definite direct object marker)", "<br>", "<br>", "", ""],
   ["בְּ", "in, at, with", "<br>", "<br>", "", ""],
   ["בוא", "(Q) to come; (Hi) bring; (Ho) be brought", "<br>", "<br>", "", ""],
   ["בֵּן", "son", "<br>", "<br>", "", ""],
   ["הַ·", "the", "<br>", "<br>", "", ""],
   ["היה", "(Q) to be; (Ni) occur, happen, become", "<br>", "<br>", "", ""],
   ["וְ", "and, but", "<br>", "<br>", "", ""],
   ["כְּ", "like, as", "<br>", "<br>", "", ""],
   ["כִּי", "for, because", "<br>", "<br>", "", ""],
   ["כֹּל", "all, every", "<br>", "<br>", "", ""],
   ["לְ", "to, for", "<br>", "<br>", "", ""],
   ["לֹא", "no, not", "<br>", "<br>", "", ""],
   ["מֶ֫לֶךְ", "king", "<br>", "<br>", "", ""],
   ["מִן", "from", "<br>", "<br>", "", ""],
   ["עַל", "on, upon", "<br>", "<br>", "", ""],
   ["עשׂה", "(Q) to do, make; (Q Pass) be done, be made, be used; (Ni) be made", "<br>", "<br>", "", ""],
]

let vocab_1021_1040 = [
   ["אָב", "father", "<br>", "<br>", "", ""],
   ["אִישׁ", "man", "<br>", "<br>", "", ""],
   ["אֶ֫רֶץ", "land, earth", "<br>", "<br>", "", ""],
   ["בַּ֫יִת", "house", "<br>", "<br>", "", ""],
   ["דבר", "(Q, Pi) to speak, say", "<br>", "<br>", "", ""],
   ["דָּבָר", "word, speech, matter, thing", "<br>", "<br>", "", ""],
   ["הוּא", "he, it, that", "<br>", "<br>", "", ""],
   ["הלך", "(Q, Pi) to walk, go; (Hi) bring, lead; (Hith) walk about", "<br>", "<br>", "", ""],
   ["זֶה", "this (masc.)", "<br>", "<br>", "", ""],
   ["יָד", "hand", "<br>", "<br>", "", ""],
   ["יוֹם", "day", "<br>", "<br>", "", ""],
   ["נתן", "(Q) to give, put, set; (Q Pass, Ni) be given", "<br>", "<br>", "", ""],
   ["ס", "(abbreviation of סְתוּמָה “closed”; indicates a minor break in the text)", "<br>", "<br>", "", ""],
   ["עַד", "until, as far as", "<br>", "<br>", "", ""],
   ["עִיר", "city", "<br>", "<br>", "", ""],
   ["עַם", "people, nation", "<br>", "<br>", "", ""],
   ["פ", "(abbreviation of פְּתוּחָה “open”; indicates a major break in the text)", "<br>", "<br>", "", ""],
   ["פָּנֶה", "face (לִפְנֵי before)", "<br>", "<br>", "", ""],
   ["ראה", "(Q) to see, look; (Ni) appear; (Hi) show", "<br>", "<br>", "", ""],
   ["שׁמע", "(Q) to hear; (Ni) be heard; (Hi) cause to hear, proclaim", "<br>", "<br>", "", ""],
]

let vocab_1041_1060 = [
   ["אֶחָד", "one", "<br>", "<br>", "", ""],
   ["אִם", "if", "<br>", "<br>", "", ""],
   ["אֲנִי", "I", "<br>", "<br>", "", ""],
   ["אֵת", "with", "<br>", "<br>", "", ""],
   ["דָּוִד", "David", "<br>", "<br>", "", ""],
   ["הִנֵּה", "behold", "<br>", "<br>", "", ""],
   ["ידע", "(Q) to know; (Ni) be known, make oneself known; (Hi) make known, inform", "<br>", "<br>", "", ""],
   ["יְהוּדָה", "Judah", "<br>", "<br>", "", ""],
   ["יצא", "(Q) to go out; (Hi) bring out", "<br>", "<br>", "", ""],
   ["ישׁב", "(Q) to sit, dwell; (Ni) be inhabited; (Hi) make sit, make dwell", "<br>", "<br>", "", ""],
   ["לקח", "(Q) to take, grasp; (Q Pass) be taken; (Ni) be taken away", "<br>", "<br>", "", ""],
   ["מות", "(Q) to die; (Hi) kill, put to death; (Ho) be killed, be put to death", "<br>", "<br>", "", ""],
   ["עַ֫יִן", "eye, spring", "<br>", "<br>", "", ""],
   ["עלה", "(Q) to go up; (Ni) be lifted up, be taken up, be exalted; (Hi) cause to come up, bring up, offer up, exalt", "<br>", "<br>", "", ""],
   ["עִם", "with", "<br>", "<br>", "", ""],
   ["שׁוב", "(Q) to return; (Hi) bring back, return (someone/something); (Polel) bring back, restore", "<br>", "<br>", "", ""],
   ["שׁלח", "(Q) to send, stretch out; (Pi) send away, let go; (Pu) be sent (away)", "<br>", "<br>", "", ""],
   ["שָׁם", "there", "<br>", "<br>", "", ""],
   ["שֵׁם", "name", "<br>", "<br>", "", ""],
   ["שָׁנָה", "year", "<br>", "<br>", "", ""],
]

let vocab_1061_1080 = [
   ["אָדוֹן", "lord, master", "<br>", "<br>", "", ""],
   ["אַחַר", "after", "<br>", "<br>", "", ""],
   ["אַ֫יִן", "there is not, there is nothing", "<br>", "<br>", "", ""],
   ["אכל", "(Q) to eat, consume; (Ni) be eaten, be consumed; (Hi) feed, give to eat, cause to eat", "<br>", "<br>", "", ""],
   ["אַל", "no, not", "<br>", "<br>", "", ""],
   ["אֵ֫לֶּה", "these", "<br>", "<br>", "", ""],
   ["אִשָּׁה", "woman, wife", "<br>", "<br>", "", ""],
   ["אַתָּה", "you (masc. sg.)", "<br>", "<br>", "", ""],
   ["גַּם", "also", "<br>", "<br>", "", ""],
   ["דֶּ֫רֶךְ", "way, road", "<br>", "<br>", "", ""],
   ["הֲ", "(interrogative particle)", "<br>", "<br>", "", ""],
   ["כֹּהֵן", "priest", "<br>", "<br>", "", ""],
   ["כֵּן", "so, thus", "<br>", "<br>", "", ""],
   ["מָה", "what?", "<br>", "<br>", "", ""],
   ["מִצְרַ֫יִם", "Egypt", "<br>", "<br>", "", ""],
   ["מֹשֶׁה", "Moses", "<br>", "<br>", "", ""],
   ["נֶ֫פֶשׁ", "life, throat, soul", "<br>", "<br>", "", ""],
   ["עֶ֫בֶד", "servant, slave", "<br>", "<br>", "", ""],
   ["קרא", "(Q) to call, summon, proclaim; (Q Pass) be called, be invited; (Ni) be called, be summoned", "<br>", "<br>", "", ""],
   ["שְׁנַ֫יִם", "two", "<br>", "<br>", "", ""],
]

let vocab_1081_1100 = [
   ["אָדָם", "man, person, humanity", "<br>", "<br>", "", ""],
   ["אָח", "brother", "<br>", "<br>", "", ""],
   ["בַּת", "daughter", "<br>", "<br>", "", ""],
   ["גָּדוֹל", "great, large", "<br>", "<br>", "", ""],
   ["גּוֹי", "nation", "<br>", "<br>", "", ""],
   ["הֵם", "they (masc.)", "<br>", "<br>", "", ""],
   ["הַר", "mountain", "<br>", "<br>", "", ""],
   ["יְרוּשָׁלִַ֫ם", "Jerusalem", "<br>", "<br>", "", ""],
   ["כֹּה", "thus, here", "<br>", "<br>", "", ""],
   ["לֵב", "heart, inner self, will", "<br>", "<br>", "", ""],
   ["מֵאָה", "hundred", "<br>", "<br>", "", ""],
   ["מַ֫יִם", "water", "<br>", "<br>", "", ""],
   ["נשׂא", "(Q) to lift, bear, carry, take; (Ni) be carried, be lifted up, lift oneself up; (Pi) carry, support, exalt; (Hith) lift oneself up, exalt oneself, be exalted", "<br>", "<br>", "", ""],
   ["עבר", "(Q) to pass over, pass through, pass by; (Hi) remove, take away, bring over, cause to pass through", "<br>", "<br>", "", ""],
   ["עמד", "(Q) to stand; (Hi) make stand, appoint, station", "<br>", "<br>", "", ""],
   ["קום", "(Q) to rise, stand; (Pi) strengthen, confirm, establish; (Hi) raise up, set up, establish", "<br>", "<br>", "", ""],
   ["רֹאשׁ", "head", "<br>", "<br>", "", ""],
   ["שׂים", "(Q) to put, set, establish", "<br>", "<br>", "", ""],
   ["שָׁלֹשׁ", "three", "<br>", "<br>", "", ""],
   ["תַּ֫חַת", "under, instead of", "<br>", "<br>", "", ""],
]

let vocab_1101_1120 = [
   ["אֶ֫לֶף", "thousand", "<br>", "<br>", "", ""],
   ["אַרְבַּע", "four", "<br>", "<br>", "", ""],
   ["הִיא", "she, it", "<br>", "<br>", "", ""],
   ["חָמֵשׁ", "five", "<br>", "<br>", "", ""],
   ["טוֹב", "pleasant, good", "<br>", "<br>", "", ""],
   ["ילד", "(Q) to bear, beget; (Q Pass, Ni) be born; (Pi) be a midwife; (Hi) beget", "<br>", "<br>", "", ""],
   ["מצא", "(Q) to find; (Ni) be found", "<br>", "<br>", "", ""],
   ["מִשְׁפָּט", "judgment, justice", "<br>", "<br>", "", ""],
   ["נכה", "(Hi) to strike, smite; (Ho) be struck down, be smitten", "<br>", "<br>", "", ""],
   ["נפל", "(Q) to fall; (Hi) make fall, cast", "<br>", "<br>", "", ""],
   ["עוֹד", "again, still, longer", "<br>", "<br>", "", ""],
   ["עוֹלָם", "long period, eternity, forever", "<br>", "<br>", "", ""],
   ["עַתָּה", "now", "<br>", "<br>", "", ""],
   ["פֶּה", "mouth", "<br>", "<br>", "", ""],
   ["צָבָא", "host, army, war, service", "<br>", "<br>", "", ""],
   ["צוה", "(Pi) to command", "<br>", "<br>", "", ""],
   ["קֹ֫דֶשׁ", "holiness", "<br>", "<br>", "", ""],
   ["קוֹל", "voice", "<br>", "<br>", "", ""],
   ["שֶׁ֫בַע", "seven", "<br>", "<br>", "", ""],
   ["שׁמר", "(Q) to keep, watch, preserve; (Ni) be guarded, be careful, be on guard", "<br>", "<br>", "", ""],
]

let vocab_1121_1140 = [
   ["אֵשׁ", "fire", "<br>", "<br>", "", ""],
   ["בֵּין", "between", "<br>", "<br>", "", ""],
   ["בנה", "(Q) to build; (Ni) be built", "<br>", "<br>", "", ""],
   ["זָהָב", "gold", "<br>", "<br>", "", ""],
   ["חֶ֫רֶב", "sword", "<br>", "<br>", "", ""],
   ["יָם", "sea", "<br>", "<br>", "", ""],
   ["ירד", "(Q) to go down, descend; (Hi) bring down, take down", "<br>", "<br>", "", ""],
   ["כֶּ֫סֶף", "silver, money", "<br>", "<br>", "", ""],
   ["מִזְבֵּחַ", "altar", "<br>", "<br>", "", ""],
   ["מִי", "who?", "<br>", "<br>", "", ""],
   ["מָקוֹם", "place", "<br>", "<br>", "", ""],
   ["נָא", "please, now", "<br>", "<br>", "", ""],
   ["נְאֻם", "utterance, declaration", "<br>", "<br>", "", ""],
   ["רַב", "great, many", "<br>", "<br>", "", ""],
   ["רוּחַ", "spirit, breath, wind", "<br>", "<br>", "", ""],
   ["שַׂר", "prince, chief", "<br>", "<br>", "", ""],
   ["שָׁאוּל", "Saul", "<br>", "<br>", "", ""],
   ["שָׁמַ֫יִם", "heavens", "<br>", "<br>", "", ""],
   ["שַׁ֫עַר", "gate", "<br>", "<br>", "", ""],
   ["תָּ֫וֶךְ", "midst", "<br>", "<br>", "", ""],
]

let vocab_1141_1160 = [
   ["אֹ֫הֶל", "tent", "<br>", "<br>", "", ""],
   ["אַהֲרֹן", "Aaron", "<br>", "<br>", "", ""],
   ["אוֹ", "or", "<br>", "<br>", "", ""],
   ["אָנֹכִי", "I", "<br>", "<br>", "", ""],
   ["ברך", "(Q Pass, Pu) to be blessed; (Pi) bless", "<br>", "<br>", "", ""],
   ["דָּם", "blood", "<br>", "<br>", "", ""],
   ["יַעֲקֹב", "Jacob", "<br>", "<br>", "", ""],
   ["ירא", "(Q) to fear, be afraid; (Ni) be feared, be terrifying, be awesome", "<br>", "<br>", "", ""],
   ["כְּלִי", "utensil, weapon", "<br>", "<br>", "", ""],
   ["לֵוִי", "Levi, Levite", "<br>", "<br>", "", ""],
   ["לֶ֫חֶם", "bread, food", "<br>", "<br>", "", ""],
   ["מִלְחָמָה", "war, battle", "<br>", "<br>", "", ""],
   ["מלך", "(Q) to be king, reign; (Hi) make king, cause to reign", "<br>", "<br>", "", ""],
   ["נָבִיא", "prophet", "<br>", "<br>", "", ""],
   ["נגד", "(Hi) to tell, declare; (Ho) be told", "<br>", "<br>", "", ""],
   ["סָבִיב", "all around", "<br>", "<br>", "", ""],
   ["ענה", "(Q) to answer, reply", "<br>", "<br>", "", ""],
   ["עֵץ", "tree, wood", "<br>", "<br>", "", ""],
   ["רַע", "bad, evil", "<br>", "<br>", "", ""],
   ["שָׂדֶה", "field", "<br>", "<br>", "", ""],
]

let vocab_1161_1180 = [
   ["אֹיֵב", "enemy", "<br>", "<br>", "", ""],
   ["אַתֶּם", "you (masc. pl.)", "<br>", "<br>", "", ""],
   ["בְּרִית", "covenant", "<br>", "<br>", "", ""],
   ["חֹ֫דֶשׁ", "month", "<br>", "<br>", "", ""],
   ["חזק", "(Q) to be strong; (Pi) strengthen, harden; (Hi) hold, seize; (Hith) strengthen oneself, become strong", "<br>", "<br>", "", ""],
   ["חַטָּאת", "sin, sin offering", "<br>", "<br>", "", ""],
   ["חיה", "(Q) to live, be alive; (Pi) revive, give life; (Hi) keep alive", "<br>", "<br>", "", ""],
   ["כרת", "(Q) to cut; (Ni) be cut off; (Hi) cut off", "<br>", "<br>", "", ""],
   ["מְאֹד", "very", "<br>", "<br>", "", ""],
   ["מִשְׁפָּחָה", "family, clan", "<br>", "<br>", "", ""],
   ["סור", "(Q) to turn aside; (Hi) remove", "<br>", "<br>", "", ""],
   ["עבד", "(Q) to work, serve", "<br>", "<br>", "", ""],
   ["עֹלָה", "burnt offering", "<br>", "<br>", "", ""],
   ["עֶשְׂרִים", "twenty", "<br>", "<br>", "", ""],
   ["עֵת", "time", "<br>", "<br>", "", ""],
   ["פְּלִשְׁתִּי", "Philistine", "<br>", "<br>", "", ""],
   ["פקד", "(Q) to visit, inspect, number; (Q Pass) be listed, be numbered; (Ni) be appointed, be visited; (Hi) appoint", "<br>", "<br>", "", ""],
   ["קרב", "(Q) to draw near; (Hi) bring near, offer", "<br>", "<br>", "", ""],
   ["רָעָה", "evil, calamity", "<br>", "<br>", "", ""],
   ["שְׁלֹמֹה", "Solomon", "<br>", "<br>", "", ""],
]

let vocab_1181_1200 = [
   ["אֶ֫בֶן", "stone", "<br>", "<br>", "", ""],
   ["אַמָּה", "cubit (unit of measure)", "<br>", "<br>", "", ""],
   ["אַף", "nose, anger", "<br>", "<br>", "", ""],
   ["בָּבֶל", "Babylon", "<br>", "<br>", "", ""],
   ["בָּשָׂר", "flesh", "<br>", "<br>", "", ""],
   ["גְּבוּל", "border", "<br>", "<br>", "", ""],
   ["חַי", "alive, living", "<br>", "<br>", "", ""],
   ["חַ֫יִל", "strength, wealth, army", "<br>", "<br>", "", ""],
   ["חֶ֫סֶד", "lovingkindness, faithfulness", "<br>", "<br>", "", ""],
   ["לֵבָב", "heart, inner self, will", "<br>", "<br>", "", ""],
   ["לְמַ֫עַן", "because of, in order that, for the sake of", "<br>", "<br>", "", ""],
   ["מִדְבָּר", "wilderness", "<br>", "<br>", "", ""],
   ["מַטֶּה", "tribe, staff", "<br>", "<br>", "", ""],
   ["מלא", "(Q) to be full, fill; (Ni) be filled, be full; (Pi) fill", "<br>", "<br>", "", ""],
   ["נַ֫עַר", "boy, youth", "<br>", "<br>", "", ""],
   ["פַּרְעֹה", "Pharaoh", "<br>", "<br>", "", ""],
   ["צֹאן", "flock, sheep", "<br>", "<br>", "", ""],
   ["רֶ֫גֶל", "foot", "<br>", "<br>", "", ""],
   ["רָשָׁע", "wicked", "<br>", "<br>", "", ""],
   ["שֵׁשׁ", "six", "<br>", "<br>", "", ""],
]

let vocab_1201_1220 = [
   ["אֲדָמָה", "ground, earth, land", "<br>", "<br>", "", ""],
   ["אהב", "(Q) to love; (Pi) love, be a lover", "<br>", "<br>", "", ""],
   ["אֵל", "God", "<br>", "<br>", "", ""],
   ["אֵם", "mother", "<br>", "<br>", "", ""],
   ["בקשׁ", "(Pi) to seek", "<br>", "<br>", "", ""],
   ["זכר", "(Q) to remember; (Ni) be remembered, be mentioned; (Hi) mention, announce, cause to be remembered", "<br>", "<br>", "", ""],
   ["זֶ֫רַע", "seed", "<br>", "<br>", "", ""],
   ["חטא", "(Q) to sin, do wrong, miss; (Pi) purify; (Hi) cause to sin", "<br>", "<br>", "", ""],
   ["יְהוֹשׁוּעַ", "Joshua", "<br>", "<br>", "", ""],
   ["ירשׁ", "(Q) to possess; (Hi) drive out", "<br>", "<br>", "", ""],
   ["כון", "(Ni) to be prepared, be established, be right; (Hi) prepare, make firm; (Polel) establish", "<br>", "<br>", "", ""],
   ["כתב", "(Q) to write; (Q Pass, Ni) be written", "<br>", "<br>", "", ""],
   ["לַ֫יְלָה", "night", "<br>", "<br>", "", ""],
   ["מוֹעֵד", "appointed time, appointed place", "<br>", "<br>", "", ""],
   ["מַעֲשֶׂה", "work", "<br>", "<br>", "", ""],
   ["נַחֲלָה", "possession, inheritance", "<br>", "<br>", "", ""],
   ["ן", "iniquity", "<br>", "<br>", "", ""],
   ["קֶ֫רֶב", "midst", "<br>", "<br>", "", ""],
   ["שָׁלוֹם", "peace, welfare, completeness", "<br>", "<br>", "", ""],
   ["תּוֹרָה", "law, instruction", "<br>", "<br>", "", ""],
]

let vocab_1221_1240 = [
   ["אסף", "(Q) to gather; (Ni) be gathered, gather together", "<br>", "<br>", "", ""],
   ["אֲרוֹן", "ark", "<br>", "<br>", "", ""],
   ["בֶּ֫גֶד", "garment", "<br>", "<br>", "", ""],
   ["בֹּ֫קֶר", "morning", "<br>", "<br>", "", ""],
   ["יוֹסֵף", "Joseph", "<br>", "<br>", "", ""],
   ["יסף", "(Q, Hi) to add, do again, continue to do", "<br>", "<br>", "", ""],
   ["כָּבוֹד", "glory, honor, heaviness", "<br>", "<br>", "", ""],
   ["כלה", "(Q) to be complete, be finished, be gone, come to an end; (Pi) finish", "<br>", "<br>", "", ""],
   ["מַחֲנֶה", "camp", "<br>", "<br>", "", ""],
   ["מַלְאָךְ", "angel", "<br>", "<br>", "", ""],
   ["מִנְחָה", "offering", "<br>", "<br>", "", ""],
   ["נטה", "(Q) to stretch out; (Q Pass) be outstretched; (Hi) to turn (aside), incline, spread out", "<br>", "<br>", "", ""],
   ["נצל", "(Ni) to be delivered; (Hi) deliver", "<br>", "<br>", "", ""],
   ["עזב", "(Q) to forsake, leave, let go; (Q Pass) be abandoned, be forsaken, be free", "<br>", "<br>", "", ""],
   ["עָשָׂר", "ten, -teen", "<br>", "<br>", "", ""],
   ["צַדִּיק", "righteous", "<br>", "<br>", "", ""],
   ["רום", "(Q) to be high, be exalted; (Hi) raise, take up, lift up; (Polel) exalt", "<br>", "<br>", "", ""],
   ["שׁכב", "(Q) to lie down", "<br>", "<br>", "", ""],
   ["שׁפט", "(Q) to judge, decide; (Ni) be judged, enter into judgment", "<br>", "<br>", "", ""],
   ["שׁתה", "(Q) to drink", "<br>", "<br>", "", ""],
]

let vocab_1241_1260 = [
   ["אבד", "(Q) to become lost, perish; (Pi, Hi) destroy", "<br>", "<br>", "", ""],
   ["אֹ֫זֶן", "ear", "<br>", "<br>", "", ""],
   ["אֶפְרַ֫יִם", "Ephraim", "<br>", "<br>", "", ""],
   ["בְּהֵמָה", "beast, cattle", "<br>", "<br>", "", ""],
   ["בָּקָר", "cattle", "<br>", "<br>", "", ""],
   ["גלה", "(Q) to uncover, go into exile; (Ni) be revealed, reveal oneself, be exposed; (Pi) uncover; (Hi) take into exile, send into exile", "<br>", "<br>", "", ""],
   ["זָקֵן", "old, elder", "<br>", "<br>", "", ""],
   ["חָצֵר", "courtyard, village", "<br>", "<br>", "", ""],
   ["יכל", "(Q) to be able", "<br>", "<br>", "", ""],
   ["יַרְדֵּן", "Jordan", "<br>", "<br>", "", ""],
   ["ישׁע", "(Ni) to be delivered, be saved; (Hi) deliver, save", "<br>", "<br>", "", ""],
   ["כַּף", "hand", "<br>", "<br>", "", ""],
   ["מוֹאָב", "Moab", "<br>", "<br>", "", ""],
   ["מִצְוָה", "commandment", "<br>", "<br>", "", ""],
   ["סֵ֫פֶר", "document, scroll, book", "<br>", "<br>", "", ""],
   ["רִאשׁוֹן", "first, former", "<br>", "<br>", "", ""],
   ["רֵעַ", "friend, companion, fellow", "<br>", "<br>", "", ""],
   ["שֵׁ֫בֶט", "scepter, rod, tribe", "<br>", "<br>", "", ""],
   ["שׁבע", "(Ni) to swear; (Hi) make (someone) take an oath", "<br>", "<br>", "", ""],
   ["שֶׁ֫מֶן", "oil, fat", "<br>", "<br>", "", ""],
]

let vocab_1261_1280 = [
   ["אַבְרָהָם", "Abraham", "<br>", "<br>", "", ""],
   ["אַחֵר", "other, another", "<br>", "<br>", "", ""],
   ["בחר", "(Q) to choose; (Q Pass) be chosen", "<br>", "<br>", "", ""],
   ["בין", "(Q) to understand; (Ni) be discerning, be understanding; (Hi) make understand, give understanding; (Hithpolel) consider, understand", "<br>", "<br>", "", ""],
   ["בִּנְיָמִן", "Benjamin", "<br>", "<br>", "", ""],
   ["דּוֹר", "generation", "<br>", "<br>", "", ""],
   ["דרשׁ", "(Q) to seek, inquire, care for", "<br>", "<br>", "", ""],
   ["הרג", "(Q) to kill, slay; (Q Pass) be killed, be slain", "<br>", "<br>", "", ""],
   ["זֶ֫בַח", "sacrifice", "<br>", "<br>", "", ""],
   ["חוה", "(Hishtaphel) to bow down, worship", "<br>", "<br>", "", ""],
   ["חוּץ", "outside", "<br>", "<br>", "", ""],
   ["לחם", "(Ni) to fight", "<br>", "<br>", "", ""],
   ["מְלָאכָה", "work", "<br>", "<br>", "", ""],
   ["סבב", "(Q) to turn, surround, go around; (Ni) turn, be turned, surround; (Hi) turn back, make go around, bring around; (Poel) surround, go around", "<br>", "<br>", "", ""],
   ["פֶּ֫תַח", "opening, doorway, entrance", "<br>", "<br>", "", ""],
   ["קדשׁ", "(Q) to be holy, be consecrated; (Ni) show oneself holy, be consecrated; (Pi, Hi) dedicate, consecrate; (Hith) consecrate oneself", "<br>", "<br>", "", ""],
   ["רבה", "(Q) to be numerous; (Hi) make numerous", "<br>", "<br>", "", ""],
   ["רעה", "(Q) to shepherd, pasture, graze", "<br>", "<br>", "", ""],
   ["שָׂפָה", "lip, edge", "<br>", "<br>", "", ""],
   ["שׁאל", "(Q) to ask, consult", "<br>", "<br>", "", ""],
]

let vocab_1281_1300 = [
   ["אַ֫יִל", "ram, ruler", "<br>", "<br>", "", ""],
   ["אַךְ", "only, nevertheless", "<br>", "<br>", "", ""],
   ["אַשּׁוּר", "Assyria", "<br>", "<br>", "", ""],
   ["לְבַד", "alone", "<br>", "<br>", "", ""],
   ["בַּ֫עַל", "master, husband, Baal", "<br>", "<br>", "", ""],
   ["גִּבּוֹר", "mighty, warrior", "<br>", "<br>", "", ""],
   ["טמא", "(Q) to be unclean; (Ni) be defiled, defile oneself; (Pi) defile, pronounce unclean; (Hith) defile oneself", "<br>", "<br>", "", ""],
   ["כסה", "(Pi) to cover", "<br>", "<br>", "", ""],
   ["מָ֫וֶת", "death", "<br>", "<br>", "", ""],
   ["מְנַשֶּׁה", "Manasseh", "<br>", "<br>", "", ""],
   ["נֶ֫גֶד", "in front of, opposite", "<br>", "<br>", "", ""],
   ["נגע", "(Q) to touch, strike; (Hi) reach, touch, arrive", "<br>", "<br>", "", ""],
   ["נוס", "(Q) to flee", "<br>", "<br>", "", ""],
   ["צְדָקָה", "righteousness", "<br>", "<br>", "", ""],
   ["צִיּוֹן", "Zion", "<br>", "<br>", "", ""],
   ["צָפוֹן", "north", "<br>", "<br>", "", ""],
   ["רֹב", "multitude, abundance, greatness", "<br>", "<br>", "", ""],
   ["שׂמח", "(Q) to rejoice, be glad; (Pi) gladden", "<br>", "<br>", "", ""],
   ["שֶׁ֫מֶשׁ", "sun", "<br>", "<br>", "", ""],
   ["שֵׁנִי", "second", "<br>", "<br>", "", ""],
]

let vocab_1301_1320 = [
   ["אָז", "then", "<br>", "<br>", "", ""],
   ["הלל", "(Pi) to praise; (Pu) be praised; (Hith) boast, glory, be praised", "<br>", "<br>", "", ""],
   ["חָכְמָה", "wisdom", "<br>", "<br>", "", ""],
   ["חנה", "(Q) to encamp", "<br>", "<br>", "", ""],
   ["יַ֫יִן", "wine", "<br>", "<br>", "", ""],
   ["יוֹאָב", "Joab", "<br>", "<br>", "", ""],
   ["יָמִין", "right hand, south", "<br>", "<br>", "", ""],
   ["כְּמוֹ", "like, as", "<br>", "<br>", "", ""],
   ["מַ֫עַל", "above, upward", "<br>", "<br>", "", ""],
   ["מִשְׁכָּן", "tabernacle, dwelling", "<br>", "<br>", "", ""],
   ["נסע", "(Q) to pull out, set out, journey on", "<br>", "<br>", "", ""],
   ["עֲבֹדָה", "service", "<br>", "<br>", "", ""],
   ["עֵדָה", "congregation", "<br>", "<br>", "", ""],
   ["רדף", "(Q) to pursue", "<br>", "<br>", "", ""],
   ["שׂנא", "(Q, Pi) to hate", "<br>", "<br>", "", ""],
   ["שֶׁ·", "that, which, who", "<br>", "<br>", "", ""],
   ["שׁבר", "(Q) to break; (Ni) be broken; (Pi) shatter, break in pieces", "<br>", "<br>", "", ""],
   ["שׁחת", "(Pi, Hi) to ruin, destroy", "<br>", "<br>", "", ""],
   ["שְׁמוּאֵל", "Samuel", "<br>", "<br>", "", ""],
   ["שְׁמֹנֶה", "eight", "<br>", "<br>", "", ""],
]

let vocab_1321_1340 = [
   ["אַף", "also, indeed", "<br>", "<br>", "", ""],
   ["אֲרָם", "Aram", "<br>", "<br>", "", ""],
   ["גִּלְעָד", "Gilead", "<br>", "<br>", "", ""],
   ["זבח", "(Q) to sacrifice, slaughter; (Pi) sacrifice", "<br>", "<br>", "", ""],
   ["חוֹמָה", "wall", "<br>", "<br>", "", ""],
   ["חָכָם", "wise", "<br>", "<br>", "", ""],
   ["חלל", "(Ni) to be profaned, profane oneself; (Pi) profane; (Hi) begin", "<br>", "<br>", "", ""],
   ["יֵשׁ", "there is", "<br>", "<br>", "", ""],
   ["כִּסֵּא", "throne", "<br>", "<br>", "", ""],
   ["מִסְפָּר", "number", "<br>", "<br>", "", ""],
   ["נוח", "(Q) to rest; (Hi) cause to rest, place, leave (alone)", "<br>", "<br>", "", ""],
   ["נַ֫חַל", "torrent, wadi", "<br>", "<br>", "", ""],
   ["נְחֹ֫שֶׁת", "bronze", "<br>", "<br>", "", ""],
   ["סוּס", "horse", "<br>", "<br>", "", ""],
   ["עֶ֫רֶב", "evening", "<br>", "<br>", "", ""],
   ["עֶשְׂרֵה", "ten, -teen", "<br>", "<br>", "", ""],
   ["פנה", "(Q) to turn", "<br>", "<br>", "", ""],
   ["פַּר", "bull", "<br>", "<br>", "", ""],
   ["פתח", "(Q) to open; (Q Pass) be open; (Ni) be opened; (Pi) loosen, open, release", "<br>", "<br>", "", ""],
   ["קרא", "(Q) to call, summon, invite; (Q Pass) be invited; (Ni) be called, be summoned", "<br>", "<br>", "", ""],
]

let vocab_1341_1360 = [
   ["אוֹר", "light", "<br>", "<br>", "", ""],
   ["אֱמֶת", "truth, faithfulness", "<br>", "<br>", "", ""],
   ["בושׁ", "(Q) to be ashamed; (Hi) put to shame, be put to shame, act shamefully", "<br>", "<br>", "", ""],
   ["גדל", "(Q) to be great, grow up; (Pi) make great, bring up (children); (Hi) make great, magnify oneself", "<br>", "<br>", "", ""],
   ["חֵמָה", "wrath, heat", "<br>", "<br>", "", ""],
   ["חֲצִי", "half", "<br>", "<br>", "", ""],
   ["חֹק", "statute", "<br>", "<br>", "", ""],
   ["יִרְמְיָהוּ", "Jeremiah", "<br>", "<br>", "", ""],
   ["כֹּחַ", "strength", "<br>", "<br>", "", ""],
   ["נגשׁ", "(Q, Ni) to go near, come near, approach; (Hi) bring near", "<br>", "<br>", "", ""],
   ["נָשִׂיא", "leader, prince", "<br>", "<br>", "", ""],
   ["עֶ֫צֶם", "bone, self", "<br>", "<br>", "", ""],
   ["פֶּן", "lest", "<br>", "<br>", "", ""],
   ["צֶ֫דֶק", "righteousness, justice, equity", "<br>", "<br>", "", ""],
   ["קבץ", "(Q, Pi) to gather; (Ni) be gathered, gather together", "<br>", "<br>", "", ""],
   ["קבר", "(Q) to bury; (Ni) be buried", "<br>", "<br>", "", ""],
   ["קָהָל", "assembly", "<br>", "<br>", "", ""],
   ["שׁאר", "(Ni) to remain, be left over; (Hi) leave remaining", "<br>", "<br>", "", ""],
   ["שׁכן", "(Q) to settle, dwell; (Pi) cause to dwell, allow to dwell", "<br>", "<br>", "", ""],
   ["שׁלך", "(Hi) to throw; (Ho) be thrown", "<br>", "<br>", "", ""],
]

let vocab_1361_1380 = [
   ["אָחוֹת", "sister", "<br>", "<br>", "", ""],
   ["אֲנַחְנוּ", "we", "<br>", "<br>", "", ""],
   ["בְּכֹר", "firstborn", "<br>", "<br>", "", ""],
   ["בטח", "(Q) to trust, be confident", "<br>", "<br>", "", ""],
   ["חַיִּים", "life", "<br>", "<br>", "", ""],
   ["יטב", "(Q) to be pleasing; (Hi) do good, make good, do well", "<br>", "<br>", "", ""],
   ["יָשָׁר", "straight, right", "<br>", "<br>", "", ""],
   ["לכד", "(Q) to capture, take, catch; (Ni) be captured, be taken, be caught", "<br>", "<br>", "", ""],
   ["לָשׁוֹן", "tongue", "<br>", "<br>", "", ""],
   ["מִגְרָשׁ", "open land, pasture", "<br>", "<br>", "", ""],
   ["מַמְלָכָה", "kingdom", "<br>", "<br>", "", ""],
   ["נָהָר", "river", "<br>", "<br>", "", ""],
   ["עֲשָׂרָה", "ten, -teen", "<br>", "<br>", "", ""],
   ["פַּ֫עַם", "foot, step, time", "<br>", "<br>", "", ""],
   ["פְּרִי", "fruit", "<br>", "<br>", "", ""],
   ["קָדוֹשׁ", "holy", "<br>", "<br>", "", ""],
   ["רֶ֫כֶב", "chariot, upper millstone", "<br>", "<br>", "", ""],
   ["שׁלם", "(Pi) to pay, repay, complete; (Hi) make complete, make peace", "<br>", "<br>", "", ""],
   ["שׁפך", "(Q) to pour out, shed (blood)", "<br>", "<br>", "", ""],
   ["תּוֹעֵבָה", "abomination", "<br>", "<br>", "", ""],
]

let vocab_1381_1400 = [
   ["אַבְשָׁלוֹם", "Absalom", "<br>", "<br>", "", ""],
   ["בכה", "(Q) to weep", "<br>", "<br>", "", ""],
   ["בִּלְתִּי", "not, in order not to, except", "<br>", "<br>", "", ""],
   ["חשׁב", "(Q) to think, consider, plan; (Ni) be considered, be accounted, be reckoned; (Pi) consider, plan, calculate", "<br>", "<br>", "", ""],
   ["ידה", "(Hi) to praise, give thanks; (Hith) confess", "<br>", "<br>", "", ""],
   ["יִצְחָק", "Isaac", "<br>", "<br>", "", ""],
   ["כבד", "(Q) to be heavy, be weighty, be severe; (Ni) be honored, honor oneself; (Pi) honor; (Hi) make heavy, harden", "<br>", "<br>", "", ""],
   ["כָּנָף", "wing, edge", "<br>", "<br>", "", ""],
   ["נבא", "(Ni) to prophesy; (Hith) prophesy, act like a prophet, rave", "<br>", "<br>", "", ""],
   ["נֶ֫גֶב", "south country, Negev", "<br>", "<br>", "", ""],
   ["נחם", "(Ni) to be sorry, relent; (Pi) comfort", "<br>", "<br>", "", ""],
   ["עַל", "on, upon, over, above", "<br>", "<br>", "", ""],
   ["עַמּוּד", "pillar", "<br>", "<br>", "", ""],
   ["עָפָר", "dust", "<br>", "<br>", "", ""],
   ["קטר", "(Pi) to burn incense, make offerings; (Hi) burn, offer up in smoke", "<br>", "<br>", "", ""],
   ["רַק", "only", "<br>", "<br>", "", ""],
   ["שׂרף", "(Q) to burn; (Ni) be burned", "<br>", "<br>", "", ""],
   ["שַׁבָּת", "Sabbath", "<br>", "<br>", "", ""],
   ["שֹׁמְרוֹן", "Samaria", "<br>", "<br>", "", ""],
   ["שֶׁ֫קֶר", "lie, deception", "<br>", "<br>", "", ""],
]

let vocab_1401_1418 = [
   ["בָּמָה", "high place", "<br>", "<br>", "", ""],
   ["בַּ֫עַד", "behind, through", "<br>", "<br>", "", ""],
   ["גאל", "(Q) to redeem, avenge", "<br>", "<br>", "", ""],
   ["חֻקָּה", "statute", "<br>", "<br>", "", ""],
   ["יָרָבְעָם", "Jeroboam", "<br>", "<br>", "", ""],
   ["יתר", "(Ni) to be remaining, be left over; (Hi) leave remaining", "<br>", "<br>", "", ""],
   ["כֶּ֫בֶשׂ", "lamb", "<br>", "<br>", "", ""],
   ["כפר", "(Pi) to make atonement", "<br>", "<br>", "", ""],
   ["מְעַט", "little, few", "<br>", "<br>", "", ""],
   ["מַרְאֶה", "appearance", "<br>", "<br>", "", ""],
   ["ספר", "(Q) to count; (Pi) recount, declare", "<br>", "<br>", "", ""],
   ["עַמּוֹן", "Ammon", "<br>", "<br>", "", ""],
   ["רוץ", "(Q) to run", "<br>", "<br>", "", ""],
   ["רֹ֫חַב", "width", "<br>", "<br>", "", ""],
   ["רָעָב", "hunger, famine", "<br>", "<br>", "", ""],
   ["שׁכח", "(Q) to forget; (Ni) be forgotten", "<br>", "<br>", "", ""],
   ["שְׁלִישִׁי", "third", "<br>", "<br>", "", ""],
   ["תָּמִיד", "continually", "<br>", "<br>", "", ""],
]


let highfreq_decks = [
   null,
   vocab_1001_1020,
   vocab_1021_1040,
   vocab_1041_1060,
   vocab_1061_1080,
   vocab_1081_1100,
   vocab_1101_1120,
   vocab_1121_1140,
   vocab_1141_1160,
   vocab_1161_1180,
   vocab_1181_1200,
   vocab_1201_1220,
   vocab_1221_1240,
   vocab_1241_1260,
   vocab_1261_1280,
   vocab_1281_1300,
   vocab_1301_1320,
   vocab_1321_1340,
   vocab_1341_1360,
   vocab_1361_1380,
   vocab_1381_1400,
   vocab_1401_1418,
]
