
let vocab_1001_1020 = [
   ["דַּ֫עַת", "knowledge", "<br>", "<br>", "", ""],
   ["הֶ֫בֶל", "vapor, breath", "<br>", "<br>", "", ""],
   ["הַרְבֵּה", "many, much, great", "<br>", "<br>", "", ""],
   ["זֹה", "this (fem.)", "<br>", "<br>", "", ""],
   ["חֵ֫לֶק", "portion", "<br>", "<br>", "", ""],
   ["חֵ֫פֶץ", "delight, matter", "<br>", "<br>", "", ""],
   ["חֹ֫שֶׁךְ", "dark, darkness", "<br>", "<br>", "", ""],
   ["טוֹבָה", "goodness", "<br>", "<br>", "", ""],
   ["יוֹתֵר", "advantage", "<br>", "<br>", "", ""],
   ["יִתְרוֹן", "profit", "<br>", "<br>", "", ""],
   ["כְּבָר", "already", "<br>", "<br>", "", ""],
   ["כְּסִיל", "fool", "<br>", "<br>", "", ""],
   ["מִקְרֶה", "fate", "<br>", "<br>", "", ""],
   ["סִכְלוּת", "folly", "<br>", "<br>", "", ""],
   ["עמל", "(Q) to toil", "<br>", "<br>", "", ""],
   ["עָמָל", "toil", "<br>", "<br>", "", ""],
   ["עִנְיָן", "task", "<br>", "<br>", "", ""],
   ["קֹהֶ֫לֶת", "Qohelet, gatherer, preacher", "<br>", "<br>", "", ""],
   ["רְעוּת", "striving", "<br>", "<br>", "", ""],
   ["שִׂמְחָה", "pleasure, joy", "<br>", "<br>", "", ""],
]

let vocab_1021_1040 = [
   ["אחז", "(Q) to hold, take hold; (Ni) be held", "<br>", "<br>", "", ""],
   ["אַחֲרוֹן", "later, after", "<br>", "<br>", "", ""],
   ["ארך", "(Hi) to prolong, be prolonged", "<br>", "<br>", "", ""],
   ["גָּבֹהַּ", "high", "<br>", "<br>", "", ""],
   ["הוֹלֵלוֹת", "madness", "<br>", "<br>", "", ""],
   ["חכם", "(Q) to be wise; (Hith) make oneself wise", "<br>", "<br>", "", ""],
   ["כַּ֫עַס", "anger, vexation", "<br>", "<br>", "", ""],
   ["מְא֫וּמָה", "anything", "<br>", "<br>", "", ""],
   ["מִסְכֵּן", "poor", "<br>", "<br>", "", ""],
   ["נדר", "(Q) to vow", "<br>", "<br>", "", ""],
   ["נטע", "(Q) to plant", "<br>", "<br>", "", ""],
   ["סָכָל", "fool", "<br>", "<br>", "", ""],
   ["עָמֵל", "toiling", "<br>", "<br>", "", ""],
   ["עֹ֫שֶׁר", "riches", "<br>", "<br>", "", ""],
   ["צֵל", "shadow", "<br>", "<br>", "", ""],
   ["קלל", "(Pi) to curse", "<br>", "<br>", "", ""],
   ["רֶ֫שַׁע", "wickedness", "<br>", "<br>", "", ""],
   ["שׂבע", "(Q) to be satisfied, be filled", "<br>", "<br>", "", ""],
   ["שְׂחוֹק", "laughter", "<br>", "<br>", "", ""],
   ["שׁלט", "(Q) to have power, domineer; (Hi) empower", "<br>", "<br>", "", ""],
]

let vocab_1041_1060 = [
   ["בהל", "(Ni, Pi) be hasty", "<br>", "<br>", "", ""],
   ["דִּבְרָה", "cause, reason", "<br>", "<br>", "", ""],
   ["זִכָּרוֹן", "memorial, remembrance", "<br>", "<br>", "", ""],
   ["חבק", "(Q, Pi) to embrace", "<br>", "<br>", "", ""],
   ["חֶשְׁבּוֹן", "explanation, scheme, thought", "<br>", "<br>", "", ""],
   ["יָרֵא", "afraid, fearful, fearing, reverent", "<br>", "<br>", "", ""],
   ["כנס", "(Q) to gather", "<br>", "<br>", "", ""],
   ["כשׁר", "(Q) to succeed; (Hi) make succeed", "<br>", "<br>", "", ""],
   ["כִּשְׁרוֹן", "skill, profit", "<br>", "<br>", "", ""],
   ["מָלֵא", "full", "<br>", "<br>", "", ""],
   ["מלט", "(Ni) to escape; (Pi) deliver", "<br>", "<br>", "", ""],
   ["נַ֫חַת", "rest, quiet", "<br>", "<br>", "", ""],
   ["סוֹף", "end", "<br>", "<br>", "", ""],
   ["עָב", "cloud", "<br>", "<br>", "", ""],
   ["עות", "(Pi) to bend; (Pu, Hith) be bent", "<br>", "<br>", "", ""],
   ["ענה", "(Q) to be occupied, be busy", "<br>", "<br>", "", ""],
   ["עָשִׁיר", "rich", "<br>", "<br>", "", ""],
   ["עשׁק", "(Q) to oppress", "<br>", "<br>", "", ""],
   ["קֵץ", "end", "<br>", "<br>", "", ""],
   ["קרה", "(Q) to happen", "<br>", "<br>", "", ""],
]

let vocab_1061_1080 = [
   ["אֵ֫בֶל", "mourning", "<br>", "<br>", "", ""],
   ["אַהֲבָה", "love", "<br>", "<br>", "", ""],
   ["אַחֲרִית", "end", "<br>", "<br>", "", ""],
   ["אֵי זה", "what? which?", "<br>", "<br>", "", ""],
   ["אֵיךְ", "how?", "<br>", "<br>", "", ""],
   ["בֶּ֫טֶן", "belly, womb", "<br>", "<br>", "", ""],
   ["גְּבוּרָה", "might, strength", "<br>", "<br>", "", ""],
   ["גֶּ֫שֶׁם", "rain", "<br>", "<br>", "", ""],
   ["דָּרוֹם", "south", "<br>", "<br>", "", ""],
   ["הוה", "(Q) to be, become", "<br>", "<br>", "", ""],
   ["הלל", "(Poel) to be mad, make mad, make foolish", "<br>", "<br>", "", ""],
   ["זהר", "(Ni) to be warned, be careful", "<br>", "<br>", "", ""],
   ["זרח", "(Q) to rise", "<br>", "<br>", "", ""],
   ["זרע", "(Q) to sow", "<br>", "<br>", "", ""],
   ["חָדָשׁ", "new", "<br>", "<br>", "", ""],
   ["חלה", "(Q) to be sick", "<br>", "<br>", "", ""],
   ["רַעְיוֹן", "striving", "<br>", "<br>", "", ""],
   ["שַׁלִּיט", "ruler", "<br>", "<br>", "", ""],
   ["תור", "(Q) to explore, search out", "<br>", "<br>", "", ""],
   ["תקן", "(Q) to be straight; (Pi) straighten, arrange", "<br>", "<br>", "", ""],
]

let vocab_1081_1100 = [
   ["חֲלוֹם", "dream", "<br>", "<br>", "", ""],
   ["חֳלִי", "sickness", "<br>", "<br>", "", ""],
   ["חמם", "(Q) to be warm", "<br>", "<br>", "", ""],
   ["חֵן", "favor, grace", "<br>", "<br>", "", ""],
   ["חסר", "(Q) to lack; (Pi) deprive", "<br>", "<br>", "", ""],
   ["חָסֵר", "lacking", "<br>", "<br>", "", ""],
   ["חשׁך", "(Q) to be dark", "<br>", "<br>", "", ""],
   ["יֶ֫לֶד", "child, youth", "<br>", "<br>", "", ""],
   ["יַלְדוּת", "youth", "<br>", "<br>", "", ""],
   ["יָפֶה", "beautiful, appropriate", "<br>", "<br>", "", ""],
   ["כעס", "(Q) to be angry", "<br>", "<br>", "", ""],
   ["מְדִינָה", "province", "<br>", "<br>", "", ""],
   ["מְהֵרָה", "quickly", "<br>", "<br>", "", ""],
   ["מַכְאֹב", "pain, sorrow", "<br>", "<br>", "", ""],
   ["מְלֹא", "fullness", "<br>", "<br>", "", ""],
   ["משׁל", "(Q) to rule", "<br>", "<br>", "", ""],
   ["מָתוֹק", "sweet", "<br>", "<br>", "", ""],
   ["מַתַּת", "gift", "<br>", "<br>", "", ""],
   ["נָחָשׁ", "serpent", "<br>", "<br>", "", ""],
   ["נְכָסִים", "wealth, possessions", "<br>", "<br>", "", ""],
]

let vocab_1101_1120 = [
   ["נסה", "(Pi) to test, try", "<br>", "<br>", "", ""],
   ["נשׁך", "(Q) to bite", "<br>", "<br>", "", ""],
   ["ספד", "(Q) to lament", "<br>", "<br>", "", ""],
   ["עֻמָּה", "beside, according to", "<br>", "<br>", "", ""],
   ["עָמֹק", "deep", "<br>", "<br>", "", ""],
   ["עֹ֫שֶׁק", "oppression", "<br>", "<br>", "", ""],
   ["פרץ", "(Q) to tear down, break through", "<br>", "<br>", "", ""],
   ["צִפּוֹר", "bird", "<br>", "<br>", "", ""],
   ["קִנְאָה", "jealousy", "<br>", "<br>", "", ""],
   ["רושׁ", "(Q) to be poor", "<br>", "<br>", "", ""],
   ["רָחוֹק", "far", "<br>", "<br>", "", ""],
   ["רחק", "(Q) to refrain, snap", "<br>", "<br>", "", ""],
   ["רצץ", "(Q, Ni) to be crushed", "<br>", "<br>", "", ""],
   ["שָׂכָר", "reward", "<br>", "<br>", "", ""],
   ["שִׂנְאָה", "hatred", "<br>", "<br>", "", ""],
   ["שְׁבוּעָה", "oath", "<br>", "<br>", "", ""],
   ["שׁבח", "(Pi) to commend, declare fortunate", "<br>", "<br>", "", ""],
   ["שְׁגָגָה", "error, mistake", "<br>", "<br>", "", ""],
   ["שׁוּק", "street", "<br>", "<br>", "", ""],
   ["שׁיר", "(Q) to sing", "<br>", "<br>", "", ""],
]

let vocab_1121_1140 = [
   ["אוה", "(Hith) to desire", "<br>", "<br>", "", ""],
   ["אור", "(Hi) to make shine", "<br>", "<br>", "", ""],
   ["אחר", "(Pi) to delay", "<br>", "<br>", "", ""],
   ["אֵסוּר", "fetter", "<br>", "<br>", "", ""],
   ["אסר", "(Q Pass) to be bound", "<br>", "<br>", "", ""],
   ["אצל", "(Q) to reserve, keep", "<br>", "<br>", "", ""],
   ["אֲרֻבָּה", "lattice window", "<br>", "<br>", "", ""],
   ["אַרְיֵה", "lion", "<br>", "<br>", "", ""],
   ["אָרֵךְ", "long (אֶ֫רֶךְ־רוּחַ patient)", "<br>", "<br>", "", ""],
   ["אַשְׁרֵי", "blessed", "<br>", "<br>", "", ""],
   ["באשׁ", "(Hi) to make stink, make fester", "<br>", "<br>", "", ""],
   ["בּוֹר", "cistern", "<br>", "<br>", "", ""],
   ["בזה", "(Q Pass) to be despised", "<br>", "<br>", "", ""],
   ["בָּחוּר", "young man", "<br>", "<br>", "", ""],
   ["בִּטָּחוֹן", "confidence, hope", "<br>", "<br>", "", ""],
   ["בְּלִי", "without", "<br>", "<br>", "", ""],
   ["בלע", "(Pi) to devour, consume", "<br>", "<br>", "", ""],
   ["שִׁיר", "song", "<br>", "<br>", "", ""],
   ["שֵׁנָה", "sleep", "<br>", "<br>", "", ""],
   ["תקף", "(Q) to overpower; (Hi) be strong", "<br>", "<br>", "", ""],
]

let vocab_1141_1160 = [
   ["בקע", "(Q) to split", "<br>", "<br>", "", ""],
   ["ברא", "(Q) to create", "<br>", "<br>", "", ""],
   ["בַּרְזֶל", "iron", "<br>", "<br>", "", ""],
   ["בְּרֵכָה", "pool", "<br>", "<br>", "", ""],
   ["ברר", "(Q) to test", "<br>", "<br>", "", ""],
   ["גָּבֵהַּ", "haughty, proud", "<br>", "<br>", "", ""],
   ["גבר", "(Pi) to exert", "<br>", "<br>", "", ""],
   ["גָּדֵר", "wall", "<br>", "<br>", "", ""],
   ["גַּלְגַּל", "wheel", "<br>", "<br>", "", ""],
   ["גֻּלָּה", "bowl", "<br>", "<br>", "", ""],
   ["גַּנָּה", "garden", "<br>", "<br>", "", ""],
   ["גְּעָרָה", "rebuke", "<br>", "<br>", "", ""],
   ["גרע", "(Q) to reduce, take away", "<br>", "<br>", "", ""],
   ["דָּג", "fish", "<br>", "<br>", "", ""],
   ["דין", "(Q) to contend", "<br>", "<br>", "", ""],
   ["דֶּ֫לֶת", "door", "<br>", "<br>", "", ""],
   ["דִּמְעָה", "tears", "<br>", "<br>", "", ""],
   ["הָמוֹן", "wealth", "<br>", "<br>", "", ""],
   ["זְבוּב", "fly", "<br>", "<br>", "", ""],
   ["זֵ֫כֶר", "memory", "<br>", "<br>", "", ""],
]

let vocab_1161_1180 = [
   ["זְמָן", "time", "<br>", "<br>", "", ""],
   ["זְעָקָה", "shouting", "<br>", "<br>", "", ""],
   ["חבל", "(Pi) to destroy", "<br>", "<br>", "", ""],
   ["חֶ֫בֶל", "cord", "<br>", "<br>", "", ""],
   ["חבר", "(Pu) to be joined", "<br>", "<br>", "", ""],
   ["חָבֵר", "companion, friend", "<br>", "<br>", "", ""],
   ["חָגָב", "grasshopper", "<br>", "<br>", "", ""],
   ["חֶ֫דֶר", "room, chamber", "<br>", "<br>", "", ""],
   ["חוּט", "cord", "<br>", "<br>", "", ""],
   ["חושׁ", "(Q) to feel enjoyment", "<br>", "<br>", "", ""],
   ["חֵטְא", "sin", "<br>", "<br>", "", ""],
   ["חֵיק", "bosom", "<br>", "<br>", "", ""],
   ["חֹ֫פֶן", "hollow of the hand", "<br>", "<br>", "", ""],
   ["חפץ", "(Q) to delight", "<br>", "<br>", "", ""],
   ["חפר", "(Q) to dig", "<br>", "<br>", "", ""],
   ["חקר", "(Pi) to search out", "<br>", "<br>", "", ""],
   ["חֹר", "noble", "<br>", "<br>", "", ""],
   ["חֵ֫רֶם", "net", "<br>", "<br>", "", ""],
   ["חשׁה", "(Q) to be silent", "<br>", "<br>", "", ""],
   ["טָהוֹר", "clean", "<br>", "<br>", "", ""],
]

let vocab_1181_1200 = [
   ["טָמֵא", "unclean", "<br>", "<br>", "", ""],
   ["יאשׁ", "(Pi) to despair", "<br>", "<br>", "", ""],
   ["יגע", "(Pi) to weary", "<br>", "<br>", "", ""],
   ["יָגֵעַ", "wearisome", "<br>", "<br>", "", ""],
   ["יַ֫עַר", "forest", "<br>", "<br>", "", ""],
   ["יָקָר", "precious", "<br>", "<br>", "", ""],
   ["יקשׁ", "(Pu) to be snared", "<br>", "<br>", "", ""],
   ["יָרֵחַ", "moon", "<br>", "<br>", "", ""],
   ["ישׁן", "(Q) to sleep", "<br>", "<br>", "", ""],
   ["יֹ֫שֶׁר", "uprightness", "<br>", "<br>", "", ""],
   ["כַּד", "jar", "<br>", "<br>", "", ""],
   ["כּוֹכָב", "star", "<br>", "<br>", "", ""],
   ["כָּ֫כָה", "so, thus", "<br>", "<br>", "", ""],
   ["כלא", "(Q) to restrain", "<br>", "<br>", "", ""],
   ["כֶּ֫לֶב", "dog", "<br>", "<br>", "", ""],
   ["כֶּ֫סֶל", "folly", "<br>", "<br>", "", ""],
   ["כֶּ֫רֶם", "vineyard", "<br>", "<br>", "", ""],
   ["לָבָן", "white", "<br>", "<br>", "", ""],
   ["לוה", "(Q) to join", "<br>", "<br>", "", ""],
   ["לַ֫חַשׁ", "charming (of a snake)", "<br>", "<br>", "", ""],
]

let vocab_1201_1220 = [
   ["למד", "(Pi) to teach", "<br>", "<br>", "", ""],
   ["מַבּוּעַ", "fountain", "<br>", "<br>", "", ""],
   ["מַדָּע", "thought, knowledge", "<br>", "<br>", "", ""],
   ["מהר", "(Pi) to hasten", "<br>", "<br>", "", ""],
   ["מוֹתָר", "advantage", "<br>", "<br>", "", ""],
   ["מַ֫טָּה", "downward", "<br>", "<br>", "", ""],
   ["מכך", "(Ni) to sink", "<br>", "<br>", "", ""],
   ["מַלְכוּת", "kingdom", "<br>", "<br>", "", ""],
   ["מנה", "(Ni) to be counted", "<br>", "<br>", "", ""],
   ["מנע", "(Q) to withhold", "<br>", "<br>", "", ""],
   ["מעט", "(Pi) to become few", "<br>", "<br>", "", ""],
   ["מְצוֹדָה", "net", "<br>", "<br>", "", ""],
   ["מִקְנֶה", "cattle", "<br>", "<br>", "", ""],
   ["מַר", "bitter", "<br>", "<br>", "", ""],
   ["מָרוֹם", "height", "<br>", "<br>", "", ""],
   ["מַרְפֵּא", "calmness", "<br>", "<br>", "", ""],
   ["משׁך", "(Q) to stimulate, cheer", "<br>", "<br>", "", ""],
   ["מִשְׁכָּב", "bed", "<br>", "<br>", "", ""],
   ["מָשָׁל", "proverb", "<br>", "<br>", "", ""],
   ["מִשְׁתֶּה", "feast", "<br>", "<br>", "", ""],
]

let vocab_1221_1240 = [
   ["מַתָּנָה", "bribe", "<br>", "<br>", "", ""],
   ["נבע", "(Hi) to pour out", "<br>", "<br>", "", ""],
   ["נֵ֫דֶר", "vow", "<br>", "<br>", "", ""],
   ["נהג", "(Q) to lead", "<br>", "<br>", "", ""],
   ["נָכְרִי", "foreign", "<br>", "<br>", "", ""],
   ["נֵ֫פֶל", "miscarriage", "<br>", "<br>", "", ""],
   ["נצץ", "(Hi) to bloom", "<br>", "<br>", "", ""],
   ["נתק", "(Ni) to be snapped", "<br>", "<br>", "", ""],
   ["סבל", "(Hith) to be burdened", "<br>", "<br>", "", ""],
   ["סְגֻלָּה", "possession, wealth", "<br>", "<br>", "", ""],
   ["סגר", "(Pu) to be shut", "<br>", "<br>", "", ""],
   ["סִיר", "pot", "<br>", "<br>", "", ""],
   ["סִירָה", "thorn", "<br>", "<br>", "", ""],
   ["סכן", "(Ni) to be endangered", "<br>", "<br>", "", ""],
   ["עוֹף", "bird", "<br>", "<br>", "", ""],
   ["עֹז", "strength, hardness", "<br>", "<br>", "", ""],
   ["עזז", "(Q) to be strong", "<br>", "<br>", "", ""],
   ["עלם", "(Ni) to be hidden", "<br>", "<br>", "", ""],
   ["עָנִי", "poor", "<br>", "<br>", "", ""],
   ["עצב", "(Ni) to be hurt", "<br>", "<br>", "", ""],
]

let vocab_1241_1260 = [
   ["עקר", "(Q) to uproot", "<br>", "<br>", "", ""],
   ["עָרוֹם", "naked", "<br>", "<br>", "", ""],
   ["פַּח", "snare, trap", "<br>", "<br>", "", ""],
   ["פַּרְדֵּס", "orchard", "<br>", "<br>", "", ""],
   ["פרר", "(Hi) to burst", "<br>", "<br>", "", ""],
   ["פִּתְאֹם", "suddenly", "<br>", "<br>", "", ""],
   ["צמח", "(Q) to grow, sprout", "<br>", "<br>", "", ""],
   ["קְבוּרָה", "grave, burial", "<br>", "<br>", "", ""],
   ["קהה", "(Pi) to be blunt", "<br>", "<br>", "", ""],
   ["קָטָן", "small", "<br>", "<br>", "", ""],
   ["קַל", "swift", "<br>", "<br>", "", ""],
   ["קלל", "(Pilpel) to sharpen", "<br>", "<br>", "", ""],
   ["קנה", "(Q) to buy", "<br>", "<br>", "", ""],
   ["קצף", "(Q) to be angry", "<br>", "<br>", "", ""],
   ["קֶ֫צֶף", "anger, wrath", "<br>", "<br>", "", ""],
   ["קצר", "(Q) to reap", "<br>", "<br>", "", ""],
   ["קְרָב", "war", "<br>", "<br>", "", ""],
   ["קרע", "(Q) to tear", "<br>", "<br>", "", ""],
   ["רֵאשִׁית", "beginning", "<br>", "<br>", "", ""],
   ["רבב", "(Q) to multiply, increase", "<br>", "<br>", "", ""],
]

let vocab_1261_1280 = [
   ["ריק", "(Hi) to empty", "<br>", "<br>", "", ""],
   ["רֹעַ", "sadness", "<br>", "<br>", "", ""],
   ["רפא", "(Q) to heal", "<br>", "<br>", "", ""],
   ["רצה", "(Q) to accept, be pleased with", "<br>", "<br>", "", ""],
   ["רקד", "(Q) to dance", "<br>", "<br>", "", ""],
   ["רקח", "(Q) to mix spice, mix ointment", "<br>", "<br>", "", ""],
   ["רשׁע", "(Q) to be wicked", "<br>", "<br>", "", ""],
   ["שָׂבָע", "abundance", "<br>", "<br>", "", ""],
   ["שׂחק", "(Q) to laugh", "<br>", "<br>", "", ""],
   ["שְׂמֹאל", "left", "<br>", "<br>", "", ""],
   ["שָׂמֵחַ", "joyful, pleased", "<br>", "<br>", "", ""],
   ["שְׁאוֹל", "Sheol, netherworld, underworld", "<br>", "<br>", "", ""],
   ["שׁאף", "(Q) to pant, hasten", "<br>", "<br>", "", ""],
   ["שׁחח", "(Ni) to die down, grow faint", "<br>", "<br>", "", ""],
   ["שׁלשׁ", "(Pu) to be threefold", "<br>", "<br>", "", ""],
   ["שׁמם", "(Hithpoel) to destroy oneself", "<br>", "<br>", "", ""],
   ["שׁנא", "(Pu) to be changed", "<br>", "<br>", "", ""],
   ["שִׁפְחָה", "female servant, female slave", "<br>", "<br>", "", ""],
   ["שׁפל", "(Q) to be low", "<br>", "<br>", "", ""],
   ["שָׁקֵד", "almond tree", "<br>", "<br>", "", ""],
]


let ecclesiastes_decks = [
   null,
   vocab_1001_1020,
   vocab_1021_1040,
   vocab_1041_1060,
   vocab_1061_1080,
   vocab_1081_1100,
   vocab_1101_1120,
   vocab_1121_1140,
   vocab_1141_1160,
   vocab_1161_1180,
   vocab_1181_1200,
   vocab_1201_1220,
   vocab_1221_1240,
   vocab_1241_1260,
   vocab_1261_1280,
]
