
let vocab_1001_1020 = [
   ["דַּ֫עַת", "knowledge", "<br>", "<br>", "", ""],
   ["הֶ֫בֶל", "vapor, breath", "<br>", "<br>", "", ""],
   ["הַרְבֵּה", "many, much, great", "<br>", "<br>", "", ""],
   ["זֹה", "this (fem.)", "<br>", "<br>", "", ""],
   ["חֵ֫לֶק", "portion", "<br>", "<br>", "", ""],
   ["חֵ֫פֶץ", "delight, matter", "<br>", "<br>", "", ""],
   ["חֹ֫שֶׁךְ", "dark, darkness", "<br>", "<br>", "", ""],
   ["טוֹבָה", "goodness", "<br>", "<br>", "", ""],
   ["יוֹתֵר", "advantage", "<br>", "<br>", "", ""],
   ["יִתְרוֹן", "profit", "<br>", "<br>", "", ""],
   ["כְּבָר", "already", "<br>", "<br>", "", ""],
   ["כְּסִיל", "fool", "<br>", "<br>", "", ""],
   ["מִקְרֶה", "fate", "<br>", "<br>", "", ""],
   ["סִכְלוּת", "folly", "<br>", "<br>", "", ""],
   ["עמל", "(Q) to toil", "<br>", "<br>", "", ""],
   ["עָמָל", "toil", "<br>", "<br>", "", ""],
   ["עִנְיָן", "task", "<br>", "<br>", "", ""],
   ["קֹהֶ֫לֶת", "Qohelet, gatherer, preacher", "<br>", "<br>", "", ""],
   ["רְעוּת", "striving", "<br>", "<br>", "", ""],
   ["שִׂמְחָה", "pleasure, joy", "<br>", "<br>", "", ""],
]

let vocab_1021_1040 = [
   ["אחז", "(Q) to hold, take hold; (Ni) be held", "<br>", "<br>", "", ""],
   ["אַחֲרוֹן", "later, after", "<br>", "<br>", "", ""],
   ["ארך", "(Hi) to prolong, be prolonged", "<br>", "<br>", "", ""],
   ["גָּבֹהַּ", "high", "<br>", "<br>", "", ""],
   ["הוֹלֵלוֹת", "madness", "<br>", "<br>", "", ""],
   ["חכם", "(Q) to be wise; (Hith) make oneself wise", "<br>", "<br>", "", ""],
   ["כַּ֫עַס", "anger, vexation", "<br>", "<br>", "", ""],
   ["מְא֫וּמָה", "anything", "<br>", "<br>", "", ""],
   ["מִסְכֵּן", "poor", "<br>", "<br>", "", ""],
   ["נדר", "(Q) to vow", "<br>", "<br>", "", ""],
   ["נטע", "(Q) to plant", "<br>", "<br>", "", ""],
   ["סָכָל", "fool", "<br>", "<br>", "", ""],
   ["עָמֵל", "toiling", "<br>", "<br>", "", ""],
   ["עֹ֫שֶׁר", "riches", "<br>", "<br>", "", ""],
   ["צֵל", "shadow", "<br>", "<br>", "", ""],
   ["קלל", "(Pi) to curse", "<br>", "<br>", "", ""],
   ["רֶ֫שַׁע", "wickedness", "<br>", "<br>", "", ""],
   ["שׂבע", "(Q) to be satisfied, be filled", "<br>", "<br>", "", ""],
   ["שְׂחוֹק", "laughter", "<br>", "<br>", "", ""],
   ["שׁלט", "(Q) to have power, domineer; (Hi) empower", "<br>", "<br>", "", ""],
]

let vocab_1041_1060 = [
   ["בהל", "(Ni, Pi) be hasty", "<br>", "<br>", "", ""],
   ["דִּבְרָה", "cause, reason", "<br>", "<br>", "", ""],
   ["זִכָּרוֹן", "memorial, remembrance", "<br>", "<br>", "", ""],
   ["חבק", "(Q, Pi) to embrace", "<br>", "<br>", "", ""],
   ["חֶשְׁבּוֹן", "explanation, scheme, thought", "<br>", "<br>", "", ""],
   ["יָרֵא", "afraid, fearful, fearing, reverent", "<br>", "<br>", "", ""],
   ["כנס", "(Q) to gather", "<br>", "<br>", "", ""],
   ["כשׁר", "(Q) to succeed; (Hi) make succeed", "<br>", "<br>", "", ""],
   ["כִּשְׁרוֹן", "skill, profit", "<br>", "<br>", "", ""],
   ["מָלֵא", "full", "<br>", "<br>", "", ""],
   ["מלט", "(Ni) to escape; (Pi) deliver", "<br>", "<br>", "", ""],
   ["נַ֫חַת", "rest, quiet", "<br>", "<br>", "", ""],
   ["סוֹף", "end", "<br>", "<br>", "", ""],
   ["עָב", "cloud", "<br>", "<br>", "", ""],
   ["עות", "(Pi) to bend; (Pu, Hith) be bent", "<br>", "<br>", "", ""],
   ["ענה", "(Q) to be occupied, be busy", "<br>", "<br>", "", ""],
   ["עָשִׁיר", "rich", "<br>", "<br>", "", ""],
   ["עשׁק", "(Q) to oppress", "<br>", "<br>", "", ""],
   ["קֵץ", "end", "<br>", "<br>", "", ""],
   ["קרה", "(Q) to happen", "<br>", "<br>", "", ""],
]


let ecclesiastes_decks = [
   null,
   vocab_1001_1020,
   vocab_1021_1040,
   vocab_1041_1060,
]
