
let vocab_221_257 = [
   ["אָבַל", "to mourn", "Genesis 37:34<br>וַיִּקְרַע יַעֲקֹב שִׂמְלֹתָיו וַיָּשֶׂם שַׂק בְּמָתְנָיו וַיִּתְאַבֵּל עַל־בְּנֹו יָמִים רַבִּים׃", "Genesis 37:34<br>Then Jacob tore his clothes, put on sackcloth and אָבֵל for his son many days.", "🧠Women wear a veil to mourn the death of a loved one"],
   ["אָוָה", "to desire, want, crave (pi./hitp.)", "Psalm 132:13<br>כִּי־בָחַר יְהוָה בְּצִיֹּון אִוָּהּ לְמֹושָׁב לֹו׃", "Psalm 132:13<br>For the LORD has chosen Zion, he has אִוָּהּ it for his dwelling, saying,", "🧠(This kinda reminds me of &quot;Abba&quot;) God desires, longs for, and wants his children foreva&#x27; (forever)"],
   ["אוֹר", "to be bright, shine", "Genesis 44:3<br>הַבֹּקֶר אֹור וְהָאֲנָשִׁים שֻׁלְּחוּ הֵמָּה וַחֲמֹרֵיהֶם׃", "Genesis 44:3<br>As soon as the morning was אוֹר, the men were sent away, they and their donkeys.", "🧠The sun shines bright rising o&#x27;er the horizon"],
   ["אָזַן", "to hear or listen to (hif.)", "2 Samuel 22:45<br>בְּנֵי נֵכָר יִתְכַּחֲשׁוּ־לִי לִשְׁמֹועַ אֹזֶן יִשָּׁמְעוּ לִי׃", "2 Samuel 22:45<br>The foreigners submit to me; As soon as they אֹזֶן , they obey me.", "🧠(Thinking of Lucy &amp; Aslan) She will hear and listen to Azan  same 3 consonant root as the word for ear"],
   ["אָמֵץ", "to be strong, brave", "Ruth 1:18<br>וַתֵּ֕רֶא כִּֽי־מִתְאַמֶּ֥צֶת הִ֖יא לָלֶ֣כֶת אִתָּ֑הּ וַתֶּחְדַּ֖ל לְדַבֵּ֥ר אֵלֶֽיהָ", "Ruth 1:18<br>", "🧠Our mate&#x27;s going to be strong and brave for us (thinking of David approaching Goliath)"],
   ["אָפָה", "to bake", "1 Sam 28:24<br>וְלָאִשָּׁ֤ה עֵֽגֶל־מַרְבֵּק֙ בַּבַּ֔יִת וַתְּמַהֵ֖ר וַתִּזְבָּחֵ֑הוּ וַתִּקַּח־קֶ֣מַח וַתָּ֔לָשׁ וַתֹּפֵ֖הוּ מַצּֽוֹת׃", "1 Sam 28:24<br>", "🧠A Father&#x27;s job is to bake mom&#x27;s birthday cake"],
   ["אָרַב", "to lie in ambush, wait for", "1 Sam 15:5<br>וַיָּבֹ֥א שָׁא֖וּל עַד־עִ֣יר עֲמָלֵ֑ק וַיָּ֖רֶב בַּנָּֽחַל׃", "1 Sam 15:5<br>", "🧠Lie in ambush and wait for them to arive"],
   ["אָרַךְ", "to lengthen, make long", "ְGen 26:8<br>...וַיְהִ֗י כִּ֣י אָֽרְכוּ־ל֥וֹ שָׁם֙ הַיָּמִ֔ים", "ְGen 26:8<br>", "🧠We need to lengthen a rack to hang all the coats from"],
   ["אָשַׁם", "to incur guilt, be guilty", "Jer 50:7<br>כָּל־מוֹצְאֵיהֶ֣ם אֲכָל֔וּם וְצָרֵיהֶ֥ם אָמְר֖וּ לֹ֣א נֶאְשָׁ֑ם", "Jer 50:7<br>", "🧠You will incur guilt/be guilty if you are found out to be a sham"],
   ["בָּגַד", "to treat or deal faithlessly, treacherously", "1 Sam 14:33<br>וַיֹּ֣אמֶר בְּגַדְתֶּ֔ם גֹּֽלּוּ־אֵלַ֥י הַיּ֖וֹם אֶ֥בֶן גְּדוֹלָֽה׃", "1 Sam 14:33<br>", "🧠Bu&#x27; God will never deal faithlessly or treacherously with those who honor Him"],
   ["בָּדַל", "to separate, divide, distinguish (nif./hif.)", "Num 16:9<br>הַמְעַ֣ט מִכֶּ֗ם כִּֽי־הִבְדִּיל֩ אֱלֹהֵ֨י יִשְׂרָאֵ֤ל אֶתְכֶם֙ מֵעֲדַ֣ת יִשְׂרָאֵ֔ל לְהַקְרִ֥יב אֶתְכֶ֖ם אֵלָ֑יו", "Num 16:9<br>", "🧠Separate, divide, and distinguish the bad from all the good"],
   ["בָּהַל", "to be hasty, terrified", "1 Sam 28:21<br>וַתָּב֤וֹא הָֽאִשָּׁה֙ אֶל־שָׁא֔וּל וַתֵּ֖רֶא כִּי־נִבְהַ֣ל מְאֹ֑ד", "1 Sam 28:21<br>", "🧠I am terrified that the bahall (like ball) is going to be hasty and hit me in the face."],
   ["בָּזָה", "to despise, think lightly of", "1 Sam 17:42<br>וַיַּבֵּ֧ט הַפְּלִשְׁתִּ֛י וַיִּרְאֶ֥ה אֶת־דָּוִ֖ד וַיִּבְזֵ֑הוּ כִּֽי־הָיָ֣ה נַ֔עַר וְאַדְמֹנִ֖י עִם־יְפֵ֥ה מַרְאֶֽה׃", "1 Sam 17:42<br>", "🧠She thinks lightly of and despises people she thinks are bazare."],
   ["בָּזַז", "to plunder, loot", "Gen 34:27<br>בְּנֵ֣י יַעֲקֹ֗ב בָּ֚אוּ עַל־הַ֣חֲלָלִ֔ים וַיָּבֹ֖זּוּ הָעִ֑יר אֲשֶׁ֥ר טִמְּא֖וּ אֲחוֹתָֽם׃", "Gen 34:27<br>", "🧠Plunder and take the loot with bazaz (like pizazz)"],
   ["בָּחַן", "to test", "Gen 42:15<br>בְּזֹ֖את תִּבָּחֵ֑נוּ חֵ֤י פַרְעֹה֙ אִם־תֵּצְא֣וּ מִזֶּ֔ה כִּ֧י אִם־בְּב֛וֹא אֲחִיכֶ֥ם הַקָּטֹ֖ן הֵֽנָּה׃", "Gen 42:15<br>", "🧠the image of testing a piece of bacon to see if it&#x27;s done…"],
   ["בָּלַל", "to mix, confuse, pour", "Gen 11:7<br>הָ֚בָה נֵֽרְדָ֔ה וְנָבְלָ֥ה שָׁ֖ם שְׂפָתָ֑ם אֲשֶׁר֙ לֹ֣א יִשְׁמְע֔וּ אִ֖ישׁ שְׂפַ֥ת רֵעֵֽהוּ׃", "Gen 11:7<br>", "🧠Even though it&#x27;s בלל and not בבל it makes me think of Babel when God poured out his anger and mixed/confused all the languages."],
   ["בָּצַר", "to be inaccessible, fortify, enclose", "Gen 11:6<br>וְעַתָּה֙ לֹֽא־יִבָּצֵ֣ר מֵהֶ֔ם כֹּ֛ל אֲשֶׁ֥ר יָזְמ֖וּ לַֽעֲשֽׂוֹ...", "Gen 11:6<br>", "🧠Bat Tsar is fortifying, enclosing, and making the castle inaccessible"],
   ["בָּשַׁל", "to boil, cook", "1 Sam 2:15<br>וְלֹֽא־יִקַּ֧ח מִמְּךָ֛ בָּשָׂ֥ר מְבֻשָּׁ֖ל כִּ֥י אִם־חָֽי׃...", "1 Sam 2:15<br>", "🧠I&#x27;ll simply boil and cook in the ba-shawl (think being over heated and the dagesh in the bet reminds me of the in/on/with to trigger &quot;in the shawl&quot;)"],
   ["גָּבַהּ", "to be lofty, exalted", "Prov 18:12<br>לִפְנֵי־שֶׁ֭בֶר יִגְבַּ֣הּ לֵב־אִ֑ישׁ וְלִפְנֵ֖י כָב֣וֹד עֲנָוָֽה׃", "Prov 18:12<br>", "🧠The govanor (governor) is high, lofty, and exalted above the people"],
   ["גָּזַל", "to tear off, seize, rob", "Gen 21:25<br>וְהוֹכִ֥חַ אַבְרָהָ֖ם אֶת־אֲבִימֶ֑לֶךְ עַל־אֹדוֹת֙ בְּאֵ֣ר הַמַּ֔יִם אֲשֶׁ֥ר גָּזְל֖וּ עַבְדֵ֥י אֲבִימֶֽלֶךְ׃", "Gen 21:25<br>", "🧠The gazelle must hurry before it&#x27;s leg is ripped off by the Lion"],
   ["גִּיל", "to rejoice, shout with joy", "Isa 48:13<br>...רָנּ֤וּ שָׁמַ֙יִם֙ וְגִ֣ילִי אָ֔רֶץ", "Isa 48:13<br>", "🧠Giel is going to squeal and shout with joy and rejoice"],
   ["גָּמַל", "to render, do, repay, wean", "1 Sam 1:22<br>וְחַנָּ֖ה לֹ֣א עָלָ֑תָה כִּֽי־אָמְרָ֣ה לְאִישָׁ֗הּ עַ֣ד יִגָּמֵ֤ל הַנַּ֙עַר֙ וַהֲבִאֹתִ֗יו וְנִרְאָה֙ אֶת־פְּנֵ֣י יְהוָ֔ה וְיָ֥שַׁב שָׁ֖ם עַד־עוֹלָֽם׃", "1 Sam 1:22<br>", "🧠I&#x27;m going to the mall and will do whatever I need to repay and render for the item I stole."],
   ["גָּנַב", "to rob, steal, deceive", "Gen 44:8<br>וְאֵ֗יךְ נִגְנֹב֙ מִבֵּ֣ית אֲדֹנֶ֔יךָ כֶּ֖סֶף א֥וֹ זָהָֽב...", "Gen 44:8<br>", "🧠I&#x27;m gonna have to deceive her to steal and rob that."],
   ["גָּרַשׁ", "to banish, divorce, cast out", "<br>", "<br>", "🧠If you&#x27;ve gotta rash, you will be cast out, banished, and divorced"],
   ["דָּמָה", "to be like, resemble (qal); to compare, liken (pi.)", "Esther 4:13<br>וַיֹּ֥אמֶר מָרְדֳּכַ֖י לְהָשִׁ֣יב אֶל־אֶסְתֵּ֑ר אַל־תְּדַמִּ֣י בְנַפְשֵׁ֔ךְ לְהִמָּלֵ֥ט בֵּית־הַמֶּ֖לֶךְ מִכָּל־הַיְּהוּדִֽים׃", "Esther 4:13<br>", "🧠"],
   ["דָּמַם", "to be still, silent", "<br>", "<br>And the sun דָּמַם and the moon stopped... ", "🧠(Profanity warning) Damn m&#x27;am you need to be still and silent!"],
   ["הָגָה", "to moan, mutter, ponder", "<br>", "<br>Keep this Book of the Law always on your lips; הָגָה on it day and night, so that you may be careful to do everything written in it.", "🧠I mutter and moan as I ponder Hagga(i)"],
   ["הָמָה", "to make a noise, uproar, roar", "<br>", "<br>Nations הָמָה, kingdoms fall; he lifts his voice, the earth melts.", "🧠Hamma&#x27; (hammer) quietly or you&#x27;ll make a noise that will cause an uproar/roar"],
   ["הָרָה", "to conceive, be pregnant", "<br>", "<br>Whoever is הָרָה with evil conceives trouble and gives birth to disillusionment.", "🧠Harrah! She&#x27;s been trying to conceive and she&#x27;s finally pregnant!"],
   ["הָרַס", "to demolish, destroy", "<br>", "<br>I will destroy the cities of your land and הָרַס all your strongholds.", "🧠We must demolish and destroy those who are harassing the women!"],
   ["זוּב", "to flow, trickle", "<br>", "<br>", "🧠I think of this being like zoom, but then it turns into an &#x27;oof&#x27; when you realize that it&#x27;s just a slow trickle flowing in the stream"],
   ["זָמַר", "I. to sing, play an instrument (pi.); II. to trim, prune", "<br>", "<br>", "🧠Some are going to sing, some are going to play an instrument, and some are going to trim/prune the trees."],
   ["זָקֵן", "to be old", "<br>", "<br>", "🧠the old man has to use za cain to get around"],
   ["זָרָה", "to scatter, winnow", "<br>", "<br>", "🧠Like זָרַע  meaning to sew, so with זָרָה  you’re going to scatter away from the הouse (sewing/scattering are both things you do to seeds)"],
   ["זָרַק", "to scatter, sprinkle", "<br>", "<br>", "🧠(picturing a priest) He scattered the ashes and sprinkled the blood on za rock"],
   ["חָבָא", "to hide, be hidden", "<br>", "<br>", "🧠I have a peach to hide; it has to be hidden"],
   ["חָבַר", "to ally, join forces, tie", "<br>", "<br>", "🧠Have our allies join forces with us OR Have Argentina join forces with us so we can tie the knot and become allies."],
]
let vocab_258_293 = [
   ["חָבַשׁ", "to bind, bind up", "<br>", "<br>", "🧠Have Vashti to bind up and throw her from the kingdom! OR  Have Ashley bind/bind up the flowers."],
   ["חָגַר", "to gird oneself, put on a belt", "<br>", "<br>", "🧠Gird onesful, put on your belt, or you&#x27;ll look haggared. OR Her guard needs to gird himself and put on his belt"],
   ["חָכַם", "to be wise, able, skillful", "<br>", "<br>", "🧠How Come? A skillful, wise and able person can tell us."],
   ["חָלַם", "to dream", "<br>", "<br>", "🧠Her lamb likes to dream in the field. "],
   ["חָלַף", "to pass by, to vanish (qal); to replace, change (hif.)", "<br>", "<br>", "🧠Her laugh passed by and vanished. It was replaced with songs that changed. OR  (thinking of what happens when a magician performs his tricks) things vanish, are replaced/changed with other things"],
   ["חָלַץ", "to prepare for battle, equip for war", "<br>", "<br>", "🧠Hey! Let&#x27;s prepare for battle! Equip for war!"],
   ["חָמַל", "to spare, have compassion on", "<br>", "<br>", "🧠Kamala Harris spared the turkey and had compassion on it. OR Hamilton spared and had compassion on the man who killed him when he aimed to the side"],
   ["חָסָה", "to seek refuge", "<br>", "<br>", "🧠Hasa (House/Casa) is where you seek refuge."],
   ["חָצַב", "to hew, quarry", "<br>", "<br>", "🧠Hats off to everyone who hews and quarries stones."],
   ["חָקַר", "to search, investigate", "<br>", "<br>", "🧠We need to search and investigate what happened to her car."],
   ["חָרֵב", "to be dry, desolate; to attack, slaughter", "<br>", "<br>", "🧠Her river was dry and desolate long before her rival attacked and slaughtered them."],
   ["חָרַד", "to tremble, startle", "<br>", "<br>", "🧠If I ever meet Herod I will tremble in fear OR Herod startled all the babies and caused the mothers to tremble. (pronounced more like Harad)"],
   ["חָרַף", "to taunt, mock, reproach", "<br>", "<br>", "🧠Her rafters caused others to taunt and mock her, looking at her house with reproach. OR Hey Ref! Didn&#x27;t you see that?  They&#x27;re in my face mocking and taunting me.  It&#x27;s a reproach!"],
   ["חָשַׂךְ", "to restrain, refrain, hold back", "<br>", "<br>", "🧠She had to restrain and hold back the kitty who would not refrain from trying to get out of her sack. OR (thinking of Boaz and Ruth) he did not restrain, refrain or hold back from filling her sack to the brim"],
   ["חָתַם", "to affix a seal, seal", "<br>", "<br>", "🧠We need to affix the seal with hot um... wax?"],
   ["טוֹב", "to be good, do good", "<br>", "<br>", "🧠"],
   ["טָמַן", "to hide, conceal", "<br>", "<br>", "🧠To a man: hide yourself! Conceal your weapons!"],
   ["טָרַף", "to tear in pieces, rend", "<br>", "<br>", "🧠Already kind of sounds like tear off"],
   ["יָגַע", "to grow weary, toil", "<br>", "<br>", "🧠She had already begun to grow weary and to toil cuando el llego. OR Slow down or ya gonna grow weary from the hard toil of the day before noon"],
   ["יָהַב", "to give (qal impv. ms הַב or הָבָה and mp הָבוּ)", "<br>", "<br>", "🧠Ya have to give and grant me my wish"],
   ["יָחַל", "to wait, tarry, hope", "<br>", "<br>", "🧠Men wait with hope in a King&#x27;s (ya) hall, hoping he&#x27;ll grant their request"],
   ["יָלַל", "to howl, wail (hif.)", "<br>", "<br>", "🧠Yell all of you! Howl and wail."],
   ["יָנַק", "to suck, suckle", "<br>", "<br>", "🧠This makes me think of hickies because someone suckled in ya neck                 How do you enter a room if you don&#x27;t suck? You knock (yanak)"],
   ["יָסַד", "to establish, assign, found, lay foundation", "<br>", "<br>", "🧠Ya sad? Establish or found a new routine, assign yourself small tasks or lay a new  foundation for your life. OR Ya said to lay a new foundation.  It was established and assigned to the workers we found"],
   ["יָסַר", "to correct, discipline, admonish", "<br>", "<br>", "🧠Ya sorry? You should be after I corrected, disciplined and admonished you!"],
   ["יָצַב", "to take one&#x27;s stand, take a position, resist (hitp.)", "<br>", "<br>", "🧠Maybe You save (yatsav) a life if you take a position, or take a stand, or resist the Empire"],
   ["יָצַת", "to kindle, burn", "<br>", "<br>", "🧠I yell this word and YATSAT sounds similar to me yelling THATS HOT as if I&#x27;ve burned myself"],
   ["יָשַׁר", "to be upright, just, pleasing", "<br>", "<br>", "🧠Ya sure I need to go straight, then right? OR Ya sure you want to please God by living an upright and just life?"],
   ["כּוּל", "to hold, contain, provide, support", "<br>", "<br>", "🧠Hold on, contain it, keep your cool and provide for/support your family. OR (thinking of a babysitter) It&#x27;s cool to provide for, support, and contain the children in your care!"],
   ["כָּחַד", "to hide, destroy, efface", "<br>", "<br>", "🧠The כ looks like a effaced face, חide, דestroy"],
   ["כָּלַם", "to shame, disgrace, hurt", "<br>", "<br>", "🧠It&#x27;s a calamity that she was hurt, disgraced, and shamed like that."],
   ["כָּנַע", "to be humble, subdued (nif.); to humble, subdue (hif.)", "<br>", "<br>", "🧠Can I be humble and subdued? "],
   ["כָּרַע", "to bend the knee, crouch", "<br>", "<br>", "🧠If you care at all, bend the knee and crouch before the King!"],
   ["לִיץ", "to scorn, deride", "<br>", "<br>", "🧠Leets scorn and deride her."],
   ["לָקַט", "to glean, gather", "<br>", "<br>", "🧠La (the) cot will be filled with all that you gather and glean"],
   ["מָאֵן", "to refuse (pi.)", "<br>", "<br>", "🧠Ma ain&#x27;t gonna refuse when I ask &quot;pretty please&quot;"],
]
let vocab_294_329 = [
   ["מוּט", "to waiver, reel, totter, stagger, flinch", "<br>", "<br>", "🧠Arguing is a moot point if he&#x27;s unwilling to waiver."],
   ["מוּל", "to circumcise", "<br>", "<br>", "🧠We must circumcise the mule"],
   ["מָחָה", "to wipe out, blot out", "<br>", "<br>", "🧠I need to wipe out ma hair from my eyes."],
   ["מָנָה", "to count, number, reckon, assign", "<br>", "<br>", "🧠The manna (which is from מָן meaning what is it) was too much to count or number.  To distinguish this from מָנָע, they would bring the manna into the הouse"],
   ["מָנַע", "hold back, withhold", "<br>", "<br>", "🧠I ain&#x27;t gonna bring the manna to them - I must hold back and withhold."],
   ["מָעַל", "to be unfaithful", "<br>", "<br>", "🧠"],
   ["מָרָה", "to be rebellious, obstinate", "<br>", "<br>", "🧠(not to be confused with מָרָא from last year, which is &quot;to be bitter&quot;.  Naomi and her husband were rebellios and obstinate when they left Israel in search of food, and she became known as Mara"],
   ["מָשַׁךְ", "to drag, pull, draw", "Daniel 1:7<br>וַיָּשֶׂם לָהֶם שַׂר הַסָּרִיסִים שֵׁמוֹת וַיָּשֶׂם לְדָֽנִיֵּאל בֵּלְטְשַׁאצַּר וְלַֽחֲנַנְיָה שַׁדְרַךְ וּלְמִֽישָׁאֵל מֵישַׁךְ וְלַעֲזַרְיָה עֲבֵד נְגֽוֹ׃", "Daniel 1:7<br>", "🧠meshach was dragged, pulled to serve the King"],
   ["נָאַף", "to commit adultery", "<br>", "<br>", "🧠She had enough of her husband committing adultery and left."],
   ["נָאַץ", "to despise, to treat with disdain", "<br>", "<br>", "🧠You&#x27;re na-atz (nuts) to despise and treat with disdain the newly appointed King Charles!"],
   ["נָגַף", "to injure, strike", "<br>", "<br>", "🧠"],
   ["נָדַד", "to flee, wander", "<br>", "<br>", "🧠oh no!  Now dad has wandered away"],
   ["נָדַר", "to make a vow", "<br>", "<br>", "🧠(Similar to נָדָח meaning to move, thrust, banish.) Don’t vow to join na dark side (thinking Star Wars) OR Now darling, I want to vow to be yours"],
   ["נָהַג", "to lead, drive, guide", "<br>", "<br>", "🧠"],
   ["נוּעַ", "to shake, wave, tremble, totter", "<br>", "<br>", "🧠The new animals shook and trembled when the others waved hello"],
   ["נוּף", "to wield, wave, move back and forth", "<br>", "<br>", "🧠"],
   ["נָחָה", "to lead, guide", "<br>", "<br>", "🧠Now how will we get there with noone to lead and guide us?"],
   ["נָטַשׁ", "to leave, forsake", "<br>", "<br>", "🧠Don&#x27;t leave and forsake Natasha"],
   ["נָסָה", "to test, try (pi.)", "<br>", "<br>", "🧠(Similar to נָשַׂה meaning to lift or carry) Before we can move into the house, we must test and try everything to ensure it&#x27;s safe."],
   ["נָסַךְ", "to pour out", "<br>", "<br>", "🧠pour out everything that&#x27;s in your sack"],
   ["נָקַב", "to pierce, bore; to designate", "<br>", "<br>", "🧠The dentist pierces and bores in a cavity before filling it"],
   ["נָקָה", "to be free, innocent, unpunished", "<br>", "<br>", "🧠"],
   ["נָקַם", "to take revenge, avenge", "<br>", "<br>", "🧠"],
   ["נָשַׁק", "to kiss", "<br>", "<br>", "🧠We can only kiss in a shack lest someone find us!"],
   ["נָתַץ", "to tear down, demolish", "<br>", "<br>", "🧠No tats! They tear down and demolish your skin. (Sorry to anyone who has tattoos!)"],
   ["נָתַק", "to tear away", "<br>", "<br>", "🧠An attack will surely tear away the city from the kingdom"],
   ["סָלַח", "to forgive, pardon", "<br>", "<br>", "🧠She&#x27;s so lucky she was forgiven and pardoned"],
   ["סָמַךְ", "to lean, to rest, to lay, to support", "<br>", "<br>", "🧠(Similar to שָׂמַח meaning to rejoice) "],
   ["סָפַד", "to wail, lament", "<br>", "<br>", "🧠Was she going to wail and lament all night while we suffered? "],
   ["עוּד", "to witness", "<br>", "<br>", "🧠who&#x27;d stand as our witness?"],
   ["עוּף", "to fly", "<br>", "<br>", "🧠Ooo! Flying creature!"],
   ["עָצַר", "to restrain, retain, detain, shut", "<br>", "<br>", "🧠(Similar to עָזַר meaning to help) The cat is ats our door.  Detain, restrain, and catch her!"],
   ["עָרַב", "to take a pledge, stand surety for", "<br>", "<br>", "🧠The time has arrived for you to fulfill your pledge and stand surety for your brother."],
   ["עָשַׁק", "to oppress, exploit, extort", "<br>", "<br>", "🧠"],
   ["פָּגַע", "to meet, encounter [attack, molest]", "<br>", "<br>", "🧠"],
   ["פָּחַד", "to dread, fear", "<br>", "<br>", "🧠"],
]
let vocab_330_368 = [
   ["פָּלַט", "to escape, bring to safety", "<br>", "<br>", "🧠Pontius Pilate had the power to bring Jesus to safty, allowing him to escape"],
   ["פָּרָה", "to bear fruit, be fruitful", "<br>", "<br>", "🧠A pair a pears will bear fruit and be fruitful"],
   ["פָּרַח", "to bud, sprout", "<br>", "<br>", "🧠"],
   ["פָּרַץ", "to break through, break into", "<br>", "<br>", "🧠The parrots broke through it&#x27;s cage and broke into the crackers"],
   ["פָּשַׁט", "to take off, strip off, undress", "<br>", "<br>", "🧠Grandpa shot the deer, who took off (and there&#x27;s something about dressing an animal after it&#x27;s been killed that might be able to tie in here...?)"],
   ["פָּשַׁע", "to rebel, transgress", "<br>", "<br>", "🧠Porshia owners are known to rebel and transgress the speed limits!"],
   ["צָדַק", "to be just, righteous, vindicated", "<br>", "<br>", "🧠"],
   ["צוּר", "to bind, besiege", "<br>", "<br>", "🧠"],
   ["צָמַח", "to sprout, spring up", "<br>", "<br>", "🧠(Similar to שָׂמַח meaning to rejoice and סָמַךְ meaning to lean or rest) "],
   ["צָפַן", "to hide, store up, treasure", "<br>", "<br>", "🧠"],
   ["צָרַף", "to smelt, refine, test", "<br>", "<br>", "🧠"],
   ["קָדַם", "to be in front, go before, meet (pi.)", "<br>", "<br>", "🧠Cut &#x27;em off and we will be in front of them, go before them to meet the new King!"],
   ["קָהַל", "to assemble (nif.); to call an assembly, summon (hif.)", "<br>", "<br>", "🧠Summon them to the ka hall to assemble because we have called an assembly"],
   ["קָוָה", "to wait for, expect", "<br>", "<br>", "🧠"],
   ["קָנָא", "to be zealous, eager, jealous (pi./hif.)", "<br>", "<br>", "🧠Similar to כָּנַע (to be humble, subdued)"],
   ["קָצַף", "to be angry", "<br>", "<br>", "🧠(Driving) Hey! He cut us off! I am so angry!"],
   ["קָצַר", "to reap, harvest", "<br>", "<br>", "🧠Cats are going to reap the harvest"],
   ["קָרָה", "to meet, happen, befall", "<br>", "<br>", "🧠(Not to be confused with קָרָא) When he called out, we just הappened to be there and able to meet right away, lest something terrible befall him"],
   ["קָשַׁב", "to pay attention, listen carefully", "<br>", "<br>", "🧠"],
   ["קָשָׁה", "to be hard, difficult, stubborn", "<br>", "<br>", "🧠"],
   ["קָשַׁר", "to bind, tie, conspire", "<br>", "<br>", "🧠"],
   ["רָבַץ", "to lie down, crouch", "<br>", "<br>", "🧠The robots like to lie down and crouch"],
   ["רָגַז", "to be agitated, upset, perturbed; to shake, tremble", "<br>", "<br>", "🧠When regae and jazz are played together, it makes me agitated, upset, perturbed!"],
   ["רָגַל", "to explore, spy", "<br>", "<br>", "🧠"],
   ["רוּעַ", "to shout (hif.)", "<br>", "<br>", "🧠"],
   ["רוּשׁ", "to be poor", "<br>", "<br>", "🧠Rush or you will be poor"],
   ["רָחַב", "to be broad, wide (qal); to extend, make room for (hif)", "<br>", "<br>", "🧠"],
   ["רָעַשׁ", "to quake, shake", "<br>", "<br>", "🧠"],
   ["רָפָה", "to lose heart, lose courage, drop, sink (qal); to abandon, forsake (hif.)", "<br>", "<br>", "🧠"],
   ["רָצַח", "to murder, slay", "<br>", "<br>", "🧠"],
   ["רָשַׁע", "to do wrong, be guilty (qal); to do wrong, condemn as guilty, pronounce guilt (hif.)", "<br>", "<br>", "🧠Some think Russia is wrong/guilty for invading Ukraine"],
   ["שׂוּשׂ", "to exult, rejoice", "<br>", "<br>", "🧠(Similar to סוּס) The text tells us all to exult and rejoice; it pleases the Lord when you lift up your voice."],
   ["שָׂחַק", "to laugh, play", "<br>", "<br>", "🧠Playing sock hockey makes me laugh"],
   ["שָׁבָה", "to take captive", "<br>", "<br>", "🧠"],
   ["שָׁטַף", "to flood, overflow, wash off", "<br>", "<br>", "🧠Shut off the water or the sink will overflow and flood the kitchen!"],
   ["שָׁפֵל", "to be low, abased; to become low", "<br>", "<br>", "🧠"],
   ["שָׁקַט", "to be quiet, idle, undisturbed", "<br>", "<br>", "🧠Shh! A cat! Please be quiet.  We want her to remain undisturbed"],
   ["תָּלָה", "to hang, impale", "<br>", "<br>", "🧠Make the pole tallah (taller) so that we can hang and impale the tall one"],
   ["תָּעָה", "to go astray, err, stagger", "<br>", "<br>", "🧠"],
]
let vocab_568_600 = [
   ["אֶ֫דֶן", "base, socket, pedestal", "<br>", "<br>", "🧠The garden of Eden was Adam&#x27;s home base.  We hold that garden on a pedestal"],
   ["אָ֫וֶן", "sorrow, wickedness, trouble", "<br>", "<br>", "🧠Aww but then sorrow, wickedness, and trouble came when the serpent entered the garden."],
   ["אוֹצָר", "treasury, store, storehouse, treasure", "<br>", "<br>", "🧠"],
   ["אוֹת", "pledge, token (m.), sign", "<br>", "<br>", "🧠"],
   ["אֲחֻזָּה", "possession", "<br>", "<br>", "🧠"],
   ["אַחֲרוֹן", "behind, later, following; west", "<br>", "<br>", "🧠"],
   ["אַחֲרִית", "outcome, latter part, end", "<br>", "<br>", "🧠"],
   ["אֱלוֹהַּ", "god", "<br>", "<br>", "🧠"],
   ["אַלּוּף", "leader of a thousand, chief", "<br>", "<br>", "🧠"],
   ["אַלְמָנָה", "widow", "<br>", "<br>", "🧠"],
   ["אָמָה", "handmaid, female slave", "<br>", "<br>", "🧠"],
   ["אֱמוּנָה", "faithfulness, fidelity, firmness", "<br>", "<br>", "🧠"],
   ["אֵ֫מֶר", "word, speech", "<br>", "<br>", "🧠"],
   ["אֵפוֹד", "ephod", "<br>", "<br>", "🧠"],
   ["אֶ֫רֶז", "cedar", "<br>", "<br>", "🧠"],
   ["אֹ֫רַח", "path, way", "<br>", "<br>", "🧠"],
   ["אֲרִי", "lion", "<br>", "<br>", "🧠"],
   ["אַרְיֵה", "lion", "<br>", "<br>", "🧠"],
   ["אֹ֫רֶךְ", "length", "<br>", "<br>", "🧠"],
   ["אִשֶּׁה", "an offering made by fire", "<br>", "<br>", "🧠"],
   ["בּוֹר", "pit, well, cistern", "<br>", "<br>", "🧠"],
   ["בֶּ֫טֶן", "womb, belly (f.) [sometimes implying body, torso]", "<br>", "<br>", "🧠"],
   ["בָּמָה", "high place", "<br>", "<br>", "🧠"],
   ["בַּ֫עַל", "lord, ruler; owner", "<br>", "<br>", "🧠"],
   ["בַּרְזֶל", "iron", "<br>", "<br>", "🧠"],
   ["בְּרָכָה", "blessing", "<br>", "<br>", "🧠"],
   ["גָּאוֹן", "majesty, exaltation, pride", "<br>", "<br>", "🧠"],
   ["גְּבוּרָה", "might, force, strength", "<br>", "<br>", "🧠"],
   ["גִּבְעָה", "hill", "<br>", "<br>", "🧠"],
   ["גֶּ֫בֶר", "man", "<br>", "<br>", "🧠"],
   ["גּוֹרָל", "lot, thing allotted", "<br>", "<br>", "🧠"],
   ["גַּיְא", "valley", "<br>", "<br>", "🧠"],
   ["גָּמָל", "camel", "<br>", "<br>", "🧠"],
]

let all_decks = [
   null,
   vocab_221_257,
   vocab_258_293,
   vocab_294_329,
   vocab_330_368,
   vocab_568_600,
]
